module.exports = [
  {
    first_name: 'Vladislav',
    last_name: 'Kara',
    position: 'C',
    shoots: 'L',
    dob: '1998-04-20',
    draft_round: 4,
    draft_pick: 124,
    draft_year: 2017,
    league_id: '22888',
    league: 'KHL',
    ep_url: 'http://www.eliteprospects.com/player.php?player=322627',
  },
  {
    first_name: 'Nikolai',
    last_name: 'Chebykin',
    position: 'W',
    shoots: 'L',
    dob: '1997-08-01',
    draft_round: 7,
    draft_pick: 182,
    draft_year: 2016,
    league_id: '22161',
    league: 'KHL',
    ep_url: 'http://www.eliteprospects.com/player.php?player=300931',
  },
  {
    first_name: 'Vladimir',
    last_name: 'Bobylyov',
    position: 'W',
    shoots: 'L',
    dob: '1997-04-18',
    draft_round: 5,
    draft_pick: 122,
    draft_year: 2016,
    league_id: '21313',
    league: 'VHL',
    ep_url: 'http://www.eliteprospects.com/player.php?player=268059',
  },
  {
    first_name: 'Ryan',
    last_name: "O'Connell",
    position: 'D',
    shoots: 'L',
    dob: '1999-04-25',
    draft_round: 7,
    draft_pick: 203,
    draft_year: 2017,
    league_id: '36023',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/286946/ryan-o-connell',
  },
  {
    first_name: 'Joey',
    last_name: 'Anderson',
    position: 'RW',
    shoots: 'R',
    dob: '1998-06-19',
    draft_round: 3,
    draft_pick: 73,
    draft_year: 2016,
    league_id: '7297',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/247964/joey-anderson',
  },
  {
    first_name: 'Semyon',
    last_name: 'Der-Arguchintsev',
    position: 'C',
    shoots: 'R',
    dob: '2000-09-15',
    draft_round: 3,
    draft_pick: 76,
    draft_year: 2018,
    // league_id: '39846',
    // league: 'KHL',
    league_id: '7590',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/315260/semyon-der-arguchintsev',
  },
  {
    first_name: 'Mac',
    last_name: 'Hollowell',
    position: 'D',
    shoots: 'R',
    dob: '1998-09-26',
    draft_round: 4,
    draft_pick: 118,
    draft_year: 2018,
    // league_id: '60490663', // MESTIS ID
    // league_id: 'c8ff052d590070ffd158a1c4', // ECHL ID
    league_id: '7303', // AHL ID
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/267652/mac-hollowell',
  },
  {
    first_name: 'Filip',
    last_name: 'Kral',
    position: 'D',
    shoots: 'L',
    dob: '1999-10-20',
    draft_round: 5,
    draft_pick: 149,
    draft_year: 2018,
    // league_id: '23461',
    // league: 'CZE',
    league_id: '8672',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/247241/filip-kral',
  },
  {
    first_name: 'Pontus',
    last_name: 'Holmberg',
    position: 'LW',
    shoots: 'L',
    dob: '1999-03-09',
    draft_round: 6,
    draft_pick: 156,
    draft_year: 2018,
    league_id: '9134',
    league: 'AHL',
    // league_id: 'qTK-4a8Y9mMrn__pontus-holmberg',
    // team_id: 'fe02-fe02mf1FN__vaxjo-lakers',
    // league: 'SHL',
    ep_url: 'https://www.eliteprospects.com/player/265859/pontus-holmberg',
  },
  {
    first_name: 'Semyon',
    last_name: 'Kizimov',
    position: 'LW',
    shoots: 'L',
    dob: '2000-01-19',
    draft_round: 7,
    draft_pick: 211,
    draft_year: 2018,
    league_id: '25697',
    league: 'VHL',
    ep_url: 'https://www.eliteprospects.com/player/420947/semyon-kizimov',
  },
  {
    first_name: 'Nick',
    last_name: 'Robertson',
    position: 'LW',
    shoots: 'L',
    dob: '2001-09-11',
    draft_round: 2,
    draft_pick: 53,
    draft_year: 2019,
    league_id: '8610',
    league: 'AHL',
    // league_id: '7662', // OHL
    // league: 'OHL',
    ep_url: 'https://www.eliteprospects.com/player/359539/nicholas-robertson',
  },
  {
    first_name: 'Mikko',
    last_name: 'Kokkonen',
    position: 'D',
    shoots: 'L',
    dob: '2001-01-18',
    draft_round: 3,
    draft_pick: 84,
    draft_year: 2019,
    // league_id: '31128854',
    // league: 'Liiga',
    league_id: '8715',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/347571/mikko-kokkonen',
  },
  {
    first_name: 'Mikhail',
    last_name: 'Abramov',
    position: 'C',
    shoots: 'L',
    dob: '2001-03-26',
    draft_round: 4,
    draft_pick: 115,
    draft_year: 2019,
    league_id: '8887',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/514653/mikhail-abramov',
  },
  {
    first_name: 'Nick',
    last_name: 'Abruzzese',
    position: 'C',
    shoots: 'L',
    dob: '1999-06-04',
    draft_round: 4,
    draft_pick: 124,
    draft_year: 2019,
    league_id: '9563',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/201476/nick-abruzzese',
  },
  {
    first_name: 'Mike',
    last_name: 'Koster',
    position: 'D',
    shoots: 'L',
    dob: '2001-04-13',
    draft_round: 5,
    draft_pick: 146,
    draft_year: 2019,
    league_id: '35998',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/427432/mike-koster',
  },
  {
    first_name: 'Kalle',
    last_name: 'Loponen',
    position: 'D',
    shoots: 'R',
    dob: '2001-03-13',
    draft_round: 7,
    draft_pick: 204,
    draft_year: 2019,
    league_id: '30730803',
    league: 'Liiga',
    // league_id: '255011063073080359893401', // Sarja20
    // league: 'Sarja20',
    ep_url: 'https://www.eliteprospects.com/player/395424/kalle-loponen',
  },
  {
    first_name: 'Rodion',
    last_name: 'Amirov',
    position: 'LW',
    shoots: 'L',
    dob: '2001-10-02',
    draft_round: 1,
    draft_pick: 15,
    draft_year: 2020,
    league_id: '30159',
    league: 'KHL',
    ep_url: 'https://www.eliteprospects.com/player/518585/rodion-amirov',
  },
  {
    first_name: 'Roni',
    last_name: 'Hirvonen',
    position: 'C',
    shoots: 'L',
    dob: '2002-01-10',
    draft_round: 2,
    draft_pick: 59,
    draft_year: 2020,
    league_id: '32269686',
    league: 'Liiga',
    // league_id: '3125868', // WJC
    // team_id: 'FIN', // WJC
    // league: 'WJC',
    ep_url: 'https://www.eliteprospects.com/player/448946/roni-hirvonen',
  },
  {
    first_name: 'Topi',
    last_name: 'Niemela',
    position: 'D',
    shoots: 'R',
    dob: '2002-03-25',
    draft_round: 3,
    draft_pick: 64,
    draft_year: 2020,
    league_id: '31555838',
    league: 'Liiga',
    // league_id: '3125883', // WJC
    // team_id: 'FIN', // WJC
    // league: 'WJC',
    ep_url: 'https://www.eliteprospects.com/player/499424/topi-niemela',
  },
  {
    first_name: 'William',
    last_name: 'Villeneuve',
    position: 'D',
    shoots: 'R',
    dob: '2002-03-20',
    draft_round: 4,
    draft_pick: 122,
    draft_year: 2020,
    league_id: '8738',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/410562/william-villeneuve',
  },
  {
    first_name: 'Dmitry',
    last_name: 'Ovchinnikov',
    position: 'C',
    shoots: 'L',
    dob: '2002-08-19',
    draft_round: 5,
    draft_pick: 137,
    draft_year: 2020,
    league_id: '31214', // KHL
    league: 'KHL',
    // league_id: '31214', // MHL
    // league: 'MHL',
    ep_url: 'https://www.eliteprospects.com/player/534929/dmitri-ovchinnikov',
  },
  {
    first_name: 'Veeti',
    last_name: 'Miettinen',
    position: 'RW',
    shoots: 'L',
    dob: '2001-09-20',
    draft_round: 6,
    draft_pick: 168,
    draft_year: 2020,
    league_id: '56289',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/396163/veeti-miettinen',
  },
  {
    first_name: 'Axel',
    last_name: 'Rindell',
    position: 'D',
    shoots: 'R',
    dob: '2000-04-23',
    draft_round: 6,
    draft_pick: 177,
    draft_year: 2020,
    league_id: '9144',
    league: 'AHL',
    // league_id: '30439447',
    // league: 'Liiga',
    ep_url: 'https://www.eliteprospects.com/player/375833/axel-rindell',
  },
  {
    first_name: 'Joe',
    last_name: 'Miller',
    position: 'C',
    shoots: 'R',
    dob: '2002-09-15',
    draft_round: 6,
    draft_pick: 180,
    draft_year: 2020,
    league_id: '35092',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/201857/joe-miller',
  },
  {
    first_name: 'John',
    last_name: 'Fusco',
    position: 'D',
    shoots: 'R',
    dob: '2001-06-13',
    draft_round: 7,
    draft_pick: 189,
    draft_year: 2020,
    league_id: '57947',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/541027/john-fusco',
  },
  {
    first_name: 'Wyatt',
    last_name: 'Schingoethe',
    position: 'C',
    shoots: 'L',
    dob: '2002-08-03',
    draft_round: 7,
    draft_pick: 195,
    draft_year: 2020,
    league_id: '58152',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/201729/wyatt-schingoethe',
  },
  {
    first_name: 'Ryan',
    last_name: 'Tverberg',
    position: 'C',
    shoots: 'R',
    dob: '2002-01-30',
    draft_round: 7,
    draft_pick: 213,
    draft_year: 2020,
    league_id: '57164',
    league: 'NCAA',
    ep_url: 'https://www.eliteprospects.com/player/201945/ryan-tverberg',
  },
  {
    first_name: 'Alex',
    last_name: 'Steeves',
    position: 'F',
    shoots: 'L',
    dob: '1999-12-10',
    draft_round: null,
    draft_pick: null,
    draft_year: null,
    league_id: '8883',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/354353/alex-steeves',
  },
  {
    first_name: 'Matthew',
    last_name: 'Knies',
    position: 'F',
    shoots: 'L',
    dob: '2002-10-17',
    draft_round: 2,
    draft_pick: 57,
    draft_year: 2021,
    league_id: '58270',
    league: 'NCAA',
    // league_id: '3129716',
    // league: 'WJC',
    // team_id: 'USA',
    ep_url: 'https://www.eliteprospects.com/player/292083/matthew-knies',
  },
  {
    first_name: 'Ty',
    last_name: 'Voit',
    position: 'F',
    shoots: 'R',
    dob: '2003-06-10',
    draft_round: 5,
    draft_pick: 153,
    draft_year: 2021,
    league_id: '8292',
    league: 'OHL',
    ep_url: 'https://www.eliteprospects.com/player/586523/ty-voit',
  },
  {
    first_name: 'Braeden',
    last_name: 'Kressler',
    position: 'C',
    shoots: 'R',
    dob: '2003-01-05',
    draft_round: null,
    draft_pick: null,
    draft_year: null,
    league_id: '8132',
    league: 'OHL',
    ep_url: 'https://www.eliteprospects.com/player/624108/braeden-kressler',
  },
  {
    first_name: 'Pavel',
    last_name: 'Gogolev',
    position: 'LW',
    shoots: 'L',
    dob: '2000-02-19',
    draft_round: null,
    draft_pick: null,
    draft_year: null,
    league_id: '7753',
    league: 'AHL',
    ep_url: 'https://www.eliteprospects.com/player/297757/pavel-gogolev',
  },
  {
    first_name: 'Fraser',
    last_name: 'Minten',
    position: 'C',
    shoots: 'L',
    dob: '2004-07-05',
    draft_round: 2,
    draft_pick: 38,
    draft_year: 2022,
    league_id: '28468',
    league: 'WHL',
    ep_url: 'https://www.eliteprospects.com/player/529809/fraser-minten',
  },
  {
    first_name: 'Nicholas',
    last_name: 'Moldenhauer',
    position: 'C',
    shoots: 'R',
    dob: '2004-05-25',
    draft_round: 3,
    draft_pick: 95,
    draft_year: 2022,
    league_id: '9424',
    league: 'USHL',
    ep_url: 'https://www.eliteprospects.com/player/535872/nicholas-moldenhauer',
  },
  {
    first_name: 'Nikita',
    last_name: 'Grebyonkin',
    position: 'RW',
    shoots: 'L',
    dob: '2003-02-05',
    draft_round: 5,
    draft_pick: 135,
    draft_year: 2022,
    league_id: '38614',
    league: 'KHL',
    ep_url: 'https://www.eliteprospects.com/player/652832/nikita-grebyonkin',
  },
  {
    first_name: 'Brandon',
    last_name: 'Lisowsky',
    position: 'LW',
    shoots: 'L',
    dob: '2004-05-25',
    draft_round: 7,
    draft_pick: 218,
    draft_year: 2022,
    league_id: '28354',
    league: 'WHL',
    ep_url: 'https://www.eliteprospects.com/player/551574/brandon-lisowsky',
  },
]
