const qmjhl_season_id = 193;

module.exports = [
  {
    first_name: "Eemeli",
    last_name: "Rasanen",
    position: "D",
    shoots: "R",
    dob: "1999-03-06",
    draft_round: 2,
    draft_pick: 59,
    draft_year: 2017,
    league_id: 31190,
    statline_url: "https://en.khl.ru/players/31190/",
    game_statline_url: "https://en.khl.ru/players/31190/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=302228",
  },
  {
    first_name: "Rasmus",
    last_name: "Sandin",
    position: "D",
    shoots: "L",
    dob: "2000-03-07",
    draft_round: 1,
    draft_pick: 29,
    draft_year: 2018,
    league_id: 7314,
    statline_url:
      "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7314&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    game_statline_url:
      "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7314&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "https://www.eliteprospects.com/player/289453/rasmus-sandin",
  },
  {
    first_name: "Filip",
    last_name: "Kral",
    position: "D",
    shoots: "L",
    dob: "1999-10-20",
    draft_round: 5,
    draft_pick: 149,
    draft_year: 2018,
    league_id: 27960,
    statline_url:
      "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=41b145a848f4bd67&fmt=json&client_code=whl&lang=en&player_id=27960&category=seasonstats",
    game_statline_url:
      "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=41b145a848f4bd67&fmt=json&client_code=whl&lang=en&player_id=27960&category=gamebygame",
    league: "WHL",
    ep_url: "https://www.eliteprospects.com/player/247241/filip-kral",
  },
  {
    first_name: "Pontus",
    last_name: "Holmberg",
    position: "LW",
    shoots: "L",
    dob: "1999-03-09",
    draft_round: 6,
    draft_pick: 156,
    draft_year: 2018,
    league_id: 0,
    statline_url:
      "https://www.shl.se/lag/fe02-fe02mf1FN__vaxjo-lakers/qTK-4a8Y9mMrn__pontus-holmberg/statistics",
    game_statline_url:
      "https://www.shl.se/lag/fe02-fe02mf1FN__vaxjo-lakers/qTK-4a8Y9mMrn__pontus-holmberg/gamelog",
    league: "SHL",
    ep_url: "https://www.eliteprospects.com/player/265859/pontus-holmberg",
  },
  {
    first_name: "Nikolai",
    last_name: "Chebykin",
    position: "W",
    shoots: "L",
    dob: "1997-08-01",
    draft_round: 7,
    draft_pick: 182,
    draft_year: 2016,
    league_id: 22161,
    statline_url: "http://www.vhlru.ru/en/players/22161/",
    game_statline_url: "http://www.vhlru.ru/en/players/22161/games/",
    league: "VHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=300931",
  },
  {
    first_name: "Semyon",
    last_name: "Kizimov",
    position: "LW",
    shoots: "L",
    dob: "2000-01-19",
    draft_round: 7,
    draft_pick: 211,
    draft_year: 2018,
    league_id: 25697,
    statline_url: "http://www.vhlru.ru/en/players/25697/",
    game_statline_url: "http://www.vhlru.ru/en/players/25697/games/",
    league: "VHL",
    ep_url: "https://www.eliteprospects.com/player/420947/semyon-kizimov",
  },
  {
    first_name: "Justin",
    last_name: "Brazeau",
    position: "RW",
    shoots: "R",
    dob: "1998-02-02",
    draft_round: null,
    draft_pick: null,
    draft_year: null,
    league_id: 7989,
    statline_url:
      "https://www.echl.com/api/s3?q=player-5ae4e4e2e12fbdac1ee2e381.json",
    game_statline_url: "",
    // statline_url: 'https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7989&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json',
    // game_statline_url: 'https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7989&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json',
    league: "ECHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=217051",
  },
  {
    first_name: "Nick",
    last_name: "Robertson",
    position: "LW",
    shoots: "L",
    dob: "2001-09-11",
    draft_round: 2,
    draft_pick: 53,
    draft_year: 2019,
    league_id: 7662,
    statline_url:
      "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7662&category=seasonstats",
    game_statline_url:
      "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7662&category=gamebygame",
    league: "OHL",
    ep_url: "https://www.eliteprospects.com/player/359539/nicholas-robertson",
  },
  {
    first_name: "Mikko",
    last_name: "Kokkonen",
    position: "D",
    shoots: "L",
    dob: "2001-01-18",
    draft_round: 3,
    draft_pick: 84,
    draft_year: 2019,
    league_id: 31128854,
    // Liiga Links
    // statline_url: 'https://liiga.fi/fi/pelaajat/31128854/kokkonen-mikko',
    // game_statline_url: 'https://liiga.fi/fi/pelaajat/31128854/kokkonen-mikko/ottelu-ottelulta',
    statline_url: "https://liiga.fi/fi/pelaajat/31128854/kokkonen-mikko",
    game_statline_url:
      "https://liiga.fi/fi/pelaajat/31128854/kokkonen-mikko/ottelu-ottelulta",
    league: "Liiga",
    ep_url: "https://www.eliteprospects.com/player/347571/mikko-kokkonen",
  },
  {
    first_name: "Mikhail",
    last_name: "Abramov",
    position: "C",
    shoots: "L",
    dob: "2001-03-26",
    draft_round: 4,
    draft_pick: 115,
    draft_year: 2019,
    league_id: 7662,
    statline_url:
      "https://lscluster.hockeytech.com/feed/index.php?feed=widgetkit2&key=f322673b6bcae299&p=1&client_code=lhjmq&view=Teamstat&fmt=json&player_id=17871&lang=en&force_player=0&callback=json",
    game_statline_url: `https://lscluster.hockeytech.com/feed/index.php?feed=widgetkit2&key=f322673b6bcae299&client_code=lhjmq&view=Gamebygame&lang=en&season_id=${qmjhl_season_id}&fmt=json&dfdsfdsa=2fdsa&player_id=17871&force_player=0&callback=json`,
    league: "QMJHL",
    ep_url: "https://www.eliteprospects.com/player/514653/mikhail-abramov",
  },
  {
    first_name: "Nick",
    last_name: "Abruzzese",
    position: "C",
    shoots: "L",
    dob: "1999-06-04",
    draft_round: 4,
    draft_pick: 124,
    draft_year: 2019,
    league_id: 7631,
    statline_url: "http://collegehockeyinc.com/stats/players20.php?harm22",
    game_statline_url: "http://collegehockeyinc.com/stats/players20.php?harm22",
    league: "NCAA",
    ep_url: "https://www.eliteprospects.com/player/201476/nick-abruzzese",
  },
  {
    first_name: "Mike",
    last_name: "Koster",
    position: "D",
    shoots: "L",
    dob: "2001-04-13",
    draft_round: 5,
    draft_pick: 146,
    draft_year: 2019,
    league_id: 7842,
    statline_url:
      "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7842&site_id=0&key=e828f89b243dc43f&client_code=ushl&league_id=&lang=en&statsType=standard&callback=json",
    game_statline_url:
      "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7842&site_id=0&key=e828f89b243dc43f&client_code=ushl&league_id=&lang=en&statsType=standard&callback=json",
    league: "USHL",
    ep_url: "https://www.eliteprospects.com/player/427432/mike-koster",
  },
];
