const response = {
  title: 'Player Stats',
  description: 'Player Stats - Summary',
  pages: 326,
  selectedPage: 1,
  orderBy: 'points',
  orderByDescending: false,
  isLive: false,
  availableExports: ['Csv', 'Pdf'],
  updateDateTime: '2021-01-02T22:14:28.18994+01:00',
  filters: [
    {
      title: 'Saison',
      entries: [
        { name: '2020/21', alias: '2021' },
        { name: '2019/20', alias: '2020' },
        { name: '2018/19', alias: '2019' },
        { name: '2017/18', alias: '2018' },
        { name: '2016/17', alias: '2017' },
        { name: '2015/16', alias: '2016' },
        { name: '2014/15', alias: '2015' },
        { name: '2013/14', alias: '2014' },
        { name: '2012/13', alias: '2013' },
        { name: '2011/12', alias: '2012' },
        { name: '2010/11', alias: '2011' },
        { name: '2009/10', alias: '2010' },
        { name: '2008/09', alias: '2009' },
      ],
      selected: '2021',
      type: 'Dropdown',
      alias: 'Season',
    },
    { title: 'Region', entries: [{ name: 'CH', alias: '1' }], selected: '1', type: 'Dropdown', alias: 'Region' },
    { title: 'Phase', entries: [{ name: 'Regular Season', alias: '3478' }], selected: '3478', type: 'Dropdown', alias: 'Phase' },
    { title: 'Heim/Auswärts', entries: [{ name: 'Heim/Auswärts', alias: 'All' }], selected: 'All', type: 'Dropdown', alias: 'ContentType' },
    {
      title: 'Team',
      entries: [
        { name: 'Alle', alias: 'all' },
        { name: 'EHC Biel-Bienne', alias: '102128' },
        { name: 'EV Zug', alias: '101144' },
        { name: 'Fribourg-Gottéron', alias: '103138' },
        { name: 'Genève-Servette HC', alias: '103140' },
        { name: 'HC Ambri-Piotta', alias: '101152' },
        { name: 'HC Davos', alias: '101151' },
        { name: 'HC Lugano', alias: '101150' },
        { name: 'Lausanne HC', alias: '103141' },
        { name: 'SC Bern', alias: '102126' },
        { name: 'SCL Tigers', alias: '102127' },
        { name: 'SC Rapperswil-Jona Lakers', alias: '101060' },
        { name: 'ZSC Lions', alias: '101139' },
      ],
      selected: 'all',
      type: 'Dropdown',
      alias: 'teamObject',
    },
    {
      title: 'Position',
      entries: [
        { name: 'Alle', alias: 'all' },
        { name: 'Stürmer', alias: '3' },
        { name: 'Verteidiger', alias: '2' },
      ],
      selected: 'all',
      type: 'Dropdown',
      alias: 'playerPosition',
    },
    {
      title: 'Lizenz',
      entries: [
        { name: 'Alle', alias: 'all' },
        { name: 'Schweizer', alias: '0' },
        { name: 'Ausländer', alias: '1' },
      ],
      selected: 'all',
      type: 'Dropdown',
      alias: 'foreigner',
    },
  ],
  secondaryMenu: [
    { name: 'Summary', rowIdentifierKey: 'points', isOrderDescending: true, alias: 'player' },
    { name: 'Goals/Assists', rowIdentifierKey: 'goals', isOrderDescending: true, alias: 'playerGoalAssist' },
    { name: 'Shots', rowIdentifierKey: 'sogSog', isOrderDescending: true, alias: 'playerShotDetail' },
    { name: 'Penalties', rowIdentifierKey: 'pimTotal', isOrderDescending: true, alias: 'playerFoul' },
    { name: 'Shootouts', rowIdentifierKey: 'penShots', isOrderDescending: true, alias: 'playerShootout' },
    { name: 'Faceoffs Summary', rowIdentifierKey: 'faceoffs', isOrderDescending: true, alias: 'playerFaceoff' },
    { name: 'Faceoffs/Zone', rowIdentifierKey: 'faceoffsOffensive', isOrderDescending: true, alias: 'playerFaceoffZone' },
    { name: 'Faceoffs/Spiel', rowIdentifierKey: 'faceoffsOffensivePerGame', isOrderDescending: true, alias: 'playerFaceoffZoneGame' },
    { name: 'Time on ice', rowIdentifierKey: 'timeOnIcePerGame', isOrderDescending: true, alias: 'playerTimeOnIce' },
  ],
  fixTableLeft: 2,
  rowIdentifier: 1,
  highlightedPositions: null,
  header: [
    { name: 'R', description: 'Rang', align: 'center', showTooltip: true, isSortable: false, alias: 'rank' },
    { name: 'Spieler', description: 'Spielername', align: 'left', showTooltip: true, isSortable: true, alias: 'player' },
    { name: 'Team', description: 'Teamname', align: 'left', showTooltip: true, isSortable: true, alias: 'team' },
    { name: 'Pos', description: 'Spielerposition', align: 'center', showTooltip: true, isSortable: true, alias: 'position' },
    { name: 'GP', description: 'Gespielte Spiele', align: 'center', showTooltip: true, isSortable: true, alias: 'gamesPlayed' },
    { name: 'G', description: 'Tore', align: 'center', showTooltip: true, isSortable: true, alias: 'goals' },
    { name: 'A', description: 'Assists', align: 'center', showTooltip: true, isSortable: true, alias: 'assists' },
    { name: 'PTS', description: 'Punktetotal', align: 'center', showTooltip: true, isSortable: true, alias: 'points' },
    { name: 'P/GP', description: 'Punkte / Spiel', align: 'center', showTooltip: true, isSortable: true, alias: 'pointsPerGame' },
    { name: 'PIM Total', description: 'PIM Total', align: 'center', showTooltip: true, isSortable: true, alias: 'pimTotal' },
    { name: '+/-', description: 'Plus / Minus', align: 'center', showTooltip: true, isSortable: true, alias: 'plusMinus' },
  ],
  data: [
    [
      '326',
      'Ness Martin',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '0',
      '0',
      '0',
      '0.00',
      '6',
      '-7',
    ],
    [
      '325',
      'Krueger Justin',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '2',
    ],
    [
      '324',
      'Kamerzin Jérémie',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '0',
      '0',
      '0.00',
      '16',
      '-9',
    ],
    [
      '323',
      'Wick Roman',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '0',
      '0',
      '0',
      '0.00',
      '6',
      '-2',
    ],
    [
      '322',
      'Schäppi Reto',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '0',
      '0',
      '0',
      '0.00',
      '14',
      '0',
    ],
    [
      '321',
      'Riat Arnaud',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '0',
      '0',
      '0',
      '0.00',
      '14',
      '-1',
    ],
    [
      '320',
      'Melnalksnis Rihards',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-6',
    ],
    [
      '319',
      'Goi Tommaso',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '0',
      '0',
      '0',
      '0.00',
      '18',
      '-4',
    ],
    [
      '318',
      'Sartori Riccardo',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '0',
      '0',
      '0',
      '0.00',
      '8',
      '-3',
    ],
    [
      '317',
      'Pezzullo Rocco',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '0',
      '0',
      '0',
      '0.00',
      '6',
      '-4',
    ],
    [
      '316',
      'Antonietti Benjamin',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '0',
      '0',
      '0',
      '0.00',
      '14',
      '2',
    ],
    [
      '315',
      'Wetter Gian-Marco',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '14',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-4',
    ],
    [
      '314',
      'Gerber Colin',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '11',
      '0',
      '0',
      '0',
      '0.00',
      '2',
      '-3',
    ],
    [
      '313',
      'Fritsche John',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '11',
      '0',
      '0',
      '0',
      '0.00',
      '2',
      '0',
    ],
    [
      '312',
      'Wüthrich Dario',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '10',
      '0',
      '0',
      '0',
      '0.00',
      '4',
      '5',
    ],
    [
      '311',
      'In-Albon Loic',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '10',
      '0',
      '0',
      '0',
      '0.00',
      '4',
      '-6',
    ],
    [
      '310',
      'Bircher Alain',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '10',
      '0',
      '0',
      '0',
      '0.00',
      '6',
      '2',
    ],
    [
      '309',
      'Rüegsegger Stefan',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '9',
      '0',
      '0',
      '0',
      '0.00',
      '4',
      '-2',
    ],
    [
      '308',
      'Pinana Christian',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '9',
      '0',
      '0',
      '0',
      '0.00',
      '6',
      '-1',
    ],
    [
      '307',
      'Mazzolini Elia',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '9',
      '0',
      '0',
      '0',
      '0.00',
      '2',
      '-4',
    ],
    [
      '306',
      'Sannitz Raffaele',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '8',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-2',
    ],
    [
      '305',
      'Bianchi Elias',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '7',
      '0',
      '0',
      '0',
      '0.00',
      '2',
      '-3',
    ],
    [
      '304',
      'Guggenheim Bastian',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '5',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '303',
      'Bochud Colin',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '5',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '302',
      'Antonietti Eliot',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '5',
      '0',
      '0',
      '0',
      '0.00',
      '2',
      '0',
    ],
    [
      '301',
      'Langenegger Livio',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '4',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '300',
      'Kast Timothy',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '4',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '299',
      'Bichsel Lian',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '3',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '298',
      'Vedova Loic',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '297',
      'Ugazzi Nicolò',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '296',
      'Sopa Kyen',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '295',
      'Schläpfer Elvis',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '294',
      'Schaller Timotée',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '293',
      'Oejdemark Victor',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '4',
      '0',
    ],
    [
      '292',
      'Näf Santiago',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '291',
      'Guebey Enzo',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '27',
      '0',
    ],
    [
      '290',
      'Garessus Lilian',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '289',
      'Fuchs Finn',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-2',
    ],
    [
      '288',
      'Elsener Janis',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '287',
      'Döpfner Andreas',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '286',
      'Canova Jannik',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '285',
      'Burkhalter Mika',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '284',
      'Allenspach Dario',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '283',
      'Trettenes Mathias',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '282',
      'Sidler Dario',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '281',
      'Schwab Robin',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '280',
      'Riedi Willy',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '279',
      'Rehak Frantisek',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '278',
      'Pastori Michael',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '277',
      'Näser Jari',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '276',
      'Lutz Tim',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '275',
      'Jobin Gaëtan',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '274',
      'Hayes Ryan',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '273',
      'Hasler Nicolas',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '272',
      'Hänggi Yannick',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '271',
      'Gärtner Francesco',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '2',
      '-1',
    ],
    [
      '270',
      'Eugster David',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '269',
      'Dufey Josselin',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '268',
      'Delémont Noah',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '267',
      'Del Ponte Karim',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '266',
      'Brasey Benjamin',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '0',
    ],
    [
      '265',
      'Andersson Axel',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '1',
      '0',
      '0',
      '0',
      '0.00',
      '0',
      '-1',
    ],
    [
      '264',
      'Randegger Flurin',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '23',
      '0',
      '1',
      '1',
      '0.04',
      '14',
      '-5',
    ],
    [
      '263',
      'Berni Tim',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '0',
      '1',
      '1',
      '0.05',
      '2',
      '-2',
    ],
    [
      '262',
      'Gerber Beat',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '16',
      '0',
      '1',
      '1',
      '0.06',
      '12',
      '-2',
    ],
    [
      '261',
      'Stoop Lukas',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '0',
      '1',
      '1',
      '0.07',
      '18',
      '-2',
    ],
    [
      '260',
      'Schlumpf Dominik',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '0',
      '1',
      '1',
      '0.07',
      '22',
      '10',
    ],
    [
      '259',
      'Heim André',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '0',
      '1',
      '1',
      '0.07',
      '12',
      '-7',
    ],
    [
      '258',
      'Gross Nico',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '13',
      '0',
      '1',
      '1',
      '0.08',
      '6',
      '-2',
    ],
    [
      '257',
      'Zryd Miro',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '12',
      '0',
      '1',
      '1',
      '0.08',
      '0',
      '-4',
    ],
    [
      '256',
      'Zgraggen Jesse',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '12',
      '0',
      '1',
      '1',
      '0.08',
      '4',
      '1',
    ],
    [
      '255',
      'Smons Sandis',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '8',
      '0',
      '1',
      '1',
      '0.12',
      '4',
      '-1',
    ],
    [
      '254',
      'Neuenschwander Joël',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '7',
      '0',
      '1',
      '1',
      '0.14',
      '2',
      '1',
    ],
    [
      '253',
      'Olofsson Jesper',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '2',
      '0',
      '1',
      '1',
      '0.50',
      '0',
      '1',
    ],
    [
      '252',
      'Capaul Luca',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '2',
      '0',
      '1',
      '1',
      '0.50',
      '2',
      '1',
    ],
    [
      '251',
      'Bougro Jordann',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '0',
      '1',
      '1',
      '0.05',
      '6',
      '-1',
    ],
    [
      '250',
      'Barandun Davyd',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '0',
      '1',
      '1',
      '0.05',
      '4',
      '-4',
    ],
    [
      '249',
      'Gustafsson Anton',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '0',
      '1',
      '1',
      '0.06',
      '8',
      '2',
    ],
    [
      '248',
      'Dotti Zaccheo',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '0',
      '1',
      '1',
      '0.07',
      '16',
      '0',
    ],
    [
      '247',
      'Schilt Sebastian',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '14',
      '0',
      '1',
      '1',
      '0.07',
      '22',
      '-1',
    ],
    [
      '246',
      'Vouillamoz Mathieu',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '13',
      '0',
      '1',
      '1',
      '0.08',
      '4',
      '0',
    ],
    [
      '245',
      'Romanenghi Matteo',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '13',
      '0',
      '1',
      '1',
      '0.08',
      '2',
      '0',
    ],
    [
      '244',
      'Buchli Dominic',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '9',
      '0',
      '1',
      '1',
      '0.11',
      '6',
      '4',
    ],
    [
      '243',
      'Ulmer Stefan',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '8',
      '0',
      '1',
      '1',
      '0.12',
      '6',
      '-2',
    ],
    [
      '242',
      'Ruefenacht Thomas',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '8',
      '0',
      '1',
      '1',
      '0.12',
      '27',
      '-1',
    ],
    [
      '241',
      'Furrer Philippe',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '4',
      '0',
      '1',
      '1',
      '0.25',
      '2',
      '3',
    ],
    [
      '240',
      'Rossi Marco',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '1',
      '0',
      '1',
      '1',
      '1.00',
      '0',
      '0',
    ],
    [
      '239',
      'Kohler Gilian',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '1',
      '0',
      '1',
      '0.06',
      '0',
      '-1',
    ],
    [
      '238',
      'Berthon Eliot',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '1',
      '0',
      '1',
      '0.06',
      '4',
      '-4',
    ],
    [
      '237',
      'Traber Tim',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '1',
      '0',
      '1',
      '0.07',
      '16',
      '0',
    ],
    [
      '236',
      'Maurer Marco',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '14',
      '1',
      '0',
      '1',
      '0.07',
      '8',
      '1',
    ],
    [
      '235',
      'Patry Stéphane',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '10',
      '1',
      '0',
      '1',
      '0.10',
      '0',
      '0',
    ],
    [
      '234',
      'Sterchi Simon',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '5',
      '1',
      '0',
      '1',
      '0.20',
      '16',
      '-2',
    ],
    [
      '233',
      'Nussbaumer Valentin',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '0',
      '2',
      '2',
      '0.11',
      '6',
      '-5',
    ],
    [
      '232',
      'Maier Fabian',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '23',
      '0',
      '2',
      '2',
      '0.09',
      '28',
      '3',
    ],
    [
      '231',
      'Fischer Jannik',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '2',
      '2',
      '0.10',
      '58',
      '-6',
    ],
    [
      '230',
      'Le Coultre Simon',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '17',
      '0',
      '2',
      '2',
      '0.12',
      '0',
      '2',
    ],
    [
      '229',
      'Lammer Dominic',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '14',
      '0',
      '2',
      '2',
      '0.14',
      '22',
      '-1',
    ],
    [
      '228',
      'Maillard Guillaume',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '12',
      '0',
      '2',
      '2',
      '0.17',
      '4',
      '0',
    ],
    [
      '227',
      'Kienzle Lorenz',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '11',
      '0',
      '2',
      '2',
      '0.18',
      '2',
      '-7',
    ],
    [
      '226',
      'Kuonen Raphael',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '10',
      '0',
      '2',
      '2',
      '0.20',
      '0',
      '-6',
    ],
    [
      '225',
      'Sobotka Vladimir',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '4',
      '0',
      '2',
      '2',
      '0.50',
      '6',
      '1',
    ],
    [
      '224',
      'Heinen Oliver',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '2',
      '2',
      '0.10',
      '6',
      '3',
    ],
    [
      '223',
      'Dal Pian Giacomo',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '0',
      '2',
      '2',
      '0.11',
      '2',
      '-2',
    ],
    [
      '222',
      'Aeschlimann Marc',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '0',
      '2',
      '2',
      '0.11',
      '0',
      '1',
    ],
    [
      '221',
      'Trisconi Noele',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '1',
      '1',
      '2',
      '0.09',
      '8',
      '-7',
    ],
    [
      '220',
      'Ngoy Michael',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '22',
      '1',
      '1',
      '2',
      '0.09',
      '8',
      '-9',
    ],
    [
      '219',
      'Geisser Tobias',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '1',
      '1',
      '2',
      '0.11',
      '8',
      '5',
    ],
    [
      '218',
      'Berger Alain',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '1',
      '1',
      '2',
      '0.12',
      '2',
      '-1',
    ],
    [
      '217',
      'Wellinger Thomas',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '14',
      '1',
      '1',
      '2',
      '0.14',
      '2',
      '2',
    ],
    [
      '216',
      'Forster Beat',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '13',
      '1',
      '1',
      '2',
      '0.15',
      '4',
      '-9',
    ],
    [
      '215',
      'Stampfli Yanick',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '8',
      '1',
      '1',
      '2',
      '0.25',
      '0',
      '3',
    ],
    [
      '214',
      'Grossniklaus Tim',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '22',
      '1',
      '1',
      '2',
      '0.09',
      '8',
      '-13',
    ],
    [
      '213',
      'Sutter Dave',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '1',
      '1',
      '2',
      '0.10',
      '6',
      '-1',
    ],
    [
      '212',
      'Andersons Toms',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '1',
      '1',
      '2',
      '0.10',
      '18',
      '-11',
    ],
    [
      '211',
      'Huguenin Anthony',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '1',
      '1',
      '2',
      '0.11',
      '8',
      '-8',
    ],
    [
      '210',
      'Weibel Keijo',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '1',
      '1',
      '2',
      '0.12',
      '4',
      '-4',
    ],
    [
      '209',
      'Tanner Ramon',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '1',
      '1',
      '2',
      '0.12',
      '6',
      '0',
    ],
    [
      '208',
      'Neuenschwander Jan',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '1',
      '1',
      '2',
      '0.12',
      '2',
      '-3',
    ],
    [
      '207',
      'Walker Julian',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '1',
      '1',
      '2',
      '0.12',
      '8',
      '-1',
    ],
    [
      '206',
      'Sciaroni Gregory',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '1',
      '1',
      '2',
      '0.12',
      '8',
      '-3',
    ],
    [
      '205',
      'Loosli Michael',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '14',
      '1',
      '1',
      '2',
      '0.14',
      '0',
      '-2',
    ],
    [
      '204',
      'Vukovic Daniel',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '22',
      '2',
      '0',
      '2',
      '0.09',
      '8',
      '1',
    ],
    [
      '203',
      'Leone Robin',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '12',
      '2',
      '0',
      '2',
      '0.17',
      '2',
      '2',
    ],
    [
      '202',
      'Froidevaux Etienne',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '11',
      '2',
      '0',
      '2',
      '0.18',
      '0',
      '0',
    ],
    [
      '201',
      'Brodin Daniel',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '10',
      '2',
      '0',
      '2',
      '0.20',
      '6',
      '-3',
    ],
    [
      '200',
      'Fey Kevin',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '0',
      '3',
      '3',
      '0.15',
      '22',
      '-8',
    ],
    [
      '199',
      'Trutmann Dario',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '0',
      '3',
      '3',
      '0.17',
      '6',
      '-7',
    ],
    [
      '198',
      'Leeger Larri',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '0',
      '3',
      '3',
      '0.17',
      '6',
      '5',
    ],
    [
      '197',
      'Abplanalp Marc',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '16',
      '0',
      '3',
      '3',
      '0.19',
      '4',
      '-7',
    ],
    [
      '196',
      'Burren Yanik',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '13',
      '0',
      '3',
      '3',
      '0.23',
      '2',
      '3',
    ],
    [
      '195',
      'Paschoud Claude-C.',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '12',
      '0',
      '3',
      '3',
      '0.25',
      '6',
      '3',
    ],
    [
      '194',
      'Riva Elia',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '1',
      '2',
      '3',
      '0.17',
      '41',
      '-1',
    ],
    [
      '193',
      'Chiesa Alessandro',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '1',
      '2',
      '3',
      '0.17',
      '20',
      '2',
    ],
    [
      '192',
      'Miranda Marco',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '9',
      '1',
      '2',
      '3',
      '0.33',
      '0',
      '-1',
    ],
    [
      '191',
      'Cadonau Claudio',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '1',
      '2',
      '3',
      '0.15',
      '8',
      '-2',
    ],
    [
      '190',
      'Diem Dominik',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '1',
      '2',
      '3',
      '0.19',
      '0',
      '-1',
    ],
    [
      '189',
      'Forrer Sandro',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '1',
      '2',
      '3',
      '0.20',
      '10',
      '-4',
    ],
    [
      '188',
      'Völlmin Michael',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '13',
      '1',
      '2',
      '3',
      '0.23',
      '0',
      '-3',
    ],
    [
      '187',
      'Diem Nolan',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '11',
      '1',
      '2',
      '3',
      '0.27',
      '6',
      '-2',
    ],
    [
      '186',
      'Untersander Ramon',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '1',
      '2',
      '3',
      '0.17',
      '6',
      '-12',
    ],
    [
      '185',
      'Bader Thierry',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '1',
      '2',
      '3',
      '0.19',
      '20',
      '-7',
    ],
    [
      '184',
      'Pedretti Marco',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '2',
      '1',
      '3',
      '0.16',
      '2',
      '0',
    ],
    [
      '183',
      'Rohrbach Dario',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '2',
      '1',
      '3',
      '0.16',
      '4',
      '-1',
    ],
    [
      '182',
      'Simic Axel',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '2',
      '1',
      '3',
      '0.18',
      '0',
      '0',
    ],
    [
      '181',
      'Kessler Tino',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '2',
      '1',
      '3',
      '0.20',
      '2',
      '1',
    ],
    [
      '180',
      'Wolf Bernd',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '3',
      '0',
      '3',
      '0.17',
      '6',
      '3',
    ],
    [
      '179',
      'Dotti Isacco',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '8',
      '3',
      '0',
      '3',
      '0.38',
      '4',
      '2',
    ],
    [
      '178',
      'Marti Aurélien',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '4',
      '4',
      '0.19',
      '14',
      '6',
    ],
    [
      '177',
      'Morant Johann',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '0',
      '4',
      '4',
      '0.20',
      '6',
      '0',
    ],
    [
      '176',
      'Nodari Matteo',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '17',
      '0',
      '4',
      '4',
      '0.24',
      '6',
      '0',
    ],
    [
      '175',
      'Thiry Thomas',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '0',
      '4',
      '4',
      '0.27',
      '8',
      '5',
    ],
    [
      '174',
      'Dufner Mauro',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '4',
      '4',
      '0.19',
      '6',
      '1',
    ],
    [
      '173',
      'Aebischer David',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '0',
      '4',
      '4',
      '0.20',
      '4',
      '2',
    ],
    [
      '172',
      'Lardi Federico',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '0',
      '4',
      '4',
      '0.22',
      '10',
      '-6',
    ],
    [
      '171',
      'Erni Samuel',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '12',
      '0',
      '4',
      '4',
      '0.33',
      '16',
      '-4',
    ],
    [
      '170',
      'Kreis Samuel',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '16',
      '0',
      '4',
      '4',
      '0.25',
      '6',
      '5',
    ],
    [
      '169',
      'Grassi Daniele',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '1',
      '3',
      '4',
      '0.18',
      '10',
      '-3',
    ],
    [
      '168',
      'Karrer Roger',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '16',
      '1',
      '3',
      '4',
      '0.25',
      '2',
      '0',
    ],
    [
      '167',
      'Sataric Rajan',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '23',
      '1',
      '3',
      '4',
      '0.17',
      '4',
      '0',
    ],
    [
      '166',
      'Jäger Ken',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '1',
      '3',
      '4',
      '0.19',
      '6',
      '1',
    ],
    [
      '165',
      'Glauser Andrea',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '17',
      '1',
      '3',
      '4',
      '0.24',
      '4',
      '-2',
    ],
    [
      '164',
      'Smirnovs Deniss',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '1',
      '3',
      '4',
      '0.22',
      '10',
      '2',
    ],
    [
      '163',
      'Mercier Jonathan',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '1',
      '3',
      '4',
      '0.22',
      '12',
      '8',
    ],
    [
      '162',
      'Horansky Stanislav',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '1',
      '3',
      '4',
      '0.22',
      '8',
      '-4',
    ],
    [
      '161',
      'Bodenmann Simon',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '8',
      '1',
      '3',
      '4',
      '0.50',
      '4',
      '2',
    ],
    [
      '160',
      'Kneubuehler Johnny',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '2',
      '2',
      '4',
      '0.18',
      '4',
      '-4',
    ],
    [
      '159',
      'Sturny Jules',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '2',
      '2',
      '4',
      '0.19',
      '8',
      '1',
    ],
    [
      '158',
      'Henauer Mika',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '14',
      '2',
      '2',
      '4',
      '0.29',
      '25',
      '-3',
    ],
    [
      '157',
      'Knak Simon',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '11',
      '2',
      '2',
      '4',
      '0.36',
      '2',
      '4',
    ],
    [
      '156',
      "D'Agostini Matt",
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '8',
      '2',
      '2',
      '4',
      '0.50',
      '6',
      '-3',
    ],
    [
      '155',
      'Almond Cody',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '2',
      '2',
      '4',
      '0.19',
      '18',
      '1',
    ],
    [
      '154',
      'Meyer Dario',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '2',
      '2',
      '4',
      '0.21',
      '0',
      '-3',
    ],
    [
      '153',
      'Thürkauf Calvin',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '3',
      '1',
      '4',
      '0.19',
      '26',
      '6',
    ],
    [
      '152',
      'Egli Chris',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '3',
      '1',
      '4',
      '0.20',
      '4',
      '2',
    ],
    [
      '151',
      'Dostoinov Alexei',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '3',
      '1',
      '4',
      '0.25',
      '8',
      '0',
    ],
    [
      '150',
      'Gerber Jeremi',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '13',
      '3',
      '1',
      '4',
      '0.31',
      '6',
      '-2',
    ],
    [
      '149',
      'Jecker Benoit',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '0',
      '5',
      '5',
      '0.24',
      '4',
      '-3',
    ],
    [
      '148',
      'Jacquemet Arnaud',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '0',
      '5',
      '5',
      '0.28',
      '4',
      '6',
    ],
    [
      '147',
      'Ullström David',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '9',
      '0',
      '5',
      '5',
      '0.56',
      '2',
      '-1',
    ],
    [
      '146',
      'Baltisberger Phil',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '0',
      '5',
      '5',
      '0.26',
      '8',
      '6',
    ],
    [
      '145',
      'Andersson Calle',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '15',
      '1',
      '4',
      '5',
      '0.33',
      '4',
      '-11',
    ],
    [
      '144',
      'Moser Simon',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '1',
      '4',
      '5',
      '0.28',
      '18',
      '2',
    ],
    [
      '143',
      'Fohrler Tobias',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '1',
      '4',
      '5',
      '0.25',
      '20',
      '1',
    ],
    [
      '142',
      'Jörg Mauro',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '1',
      '4',
      '5',
      '0.29',
      '2',
      '1',
    ],
    [
      '141',
      'Lajunen Jani',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '10',
      '1',
      '4',
      '5',
      '0.50',
      '14',
      '-4',
    ],
    [
      '140',
      'Marchon Nathan',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '1',
      '4',
      '5',
      '0.28',
      '8',
      '0',
    ],
    [
      '139',
      'Herburger Raphael',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '2',
      '3',
      '5',
      '0.28',
      '14',
      '0',
    ],
    [
      '138',
      'Richard Tanner',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '12',
      '2',
      '3',
      '5',
      '0.42',
      '4',
      '2',
    ],
    [
      '137',
      'Kostner Diego',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '2',
      '3',
      '5',
      '0.24',
      '8',
      '-1',
    ],
    [
      '136',
      'Jelovac Igor',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '2',
      '3',
      '5',
      '0.26',
      '14',
      '2',
    ],
    [
      '135',
      'Suter Pius',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '6',
      '2',
      '3',
      '5',
      '0.83',
      '8',
      '3',
    ],
    [
      '134',
      'Walser Samuel',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '3',
      '2',
      '5',
      '0.24',
      '22',
      '2',
    ],
    [
      '133',
      'Komarek Konstantin',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '7',
      '3',
      '2',
      '5',
      '0.71',
      '0',
      '0',
    ],
    [
      '132',
      'Leuenberger Sven',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '4',
      '1',
      '5',
      '0.24',
      '8',
      '5',
    ],
    [
      '131',
      'Guerra Samuel',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '16',
      '4',
      '1',
      '5',
      '0.31',
      '6',
      '5',
    ],
    [
      '130',
      'Sigrist Justin',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '5',
      '0',
      '5',
      '0.26',
      '2',
      '0',
    ],
    [
      '129',
      'Bozon Tim',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '5',
      '0',
      '5',
      '0.26',
      '6',
      '1',
    ],
    [
      '128',
      'Stadler Livio',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '0',
      '6',
      '6',
      '0.32',
      '4',
      '11',
    ],
    [
      '127',
      'Heldner Fabian',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '1',
      '5',
      '6',
      '0.29',
      '2',
      '9',
    ],
    [
      '126',
      'Chavaillaz Benjamin',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '1',
      '5',
      '6',
      '0.33',
      '0',
      '8',
    ],
    [
      '125',
      'Suri Reto',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '2',
      '4',
      '6',
      '0.40',
      '2',
      '-3',
    ],
    [
      '124',
      'Douay Floran',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '2',
      '4',
      '6',
      '0.30',
      '28',
      '-2',
    ],
    [
      '123',
      'Thorell Erik',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '2',
      '4',
      '6',
      '0.40',
      '2',
      '-1',
    ],
    [
      '122',
      'Schmid Sandro',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '2',
      '4',
      '6',
      '0.29',
      '6',
      '-3',
    ],
    [
      '121',
      'Earl Robbie',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '14',
      '2',
      '4',
      '6',
      '0.43',
      '18',
      '2',
    ],
    [
      '120',
      'Prassl Raphael',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '3',
      '3',
      '6',
      '0.30',
      '8',
      '4',
    ],
    [
      '119',
      'Morini Giovanni',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '13',
      '3',
      '3',
      '6',
      '0.46',
      '10',
      '1',
    ],
    [
      '118',
      'Lindbohm Petteri',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '3',
      '3',
      '6',
      '0.33',
      '16',
      '1',
    ],
    [
      '117',
      'Scherwey Tristan',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '3',
      '3',
      '6',
      '0.38',
      '24',
      '0',
    ],
    [
      '116',
      'Emmerton Cory',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '14',
      '3',
      '3',
      '6',
      '0.43',
      '4',
      '7',
    ],
    [
      '115',
      'Bachofner Jérôme',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '3',
      '3',
      '6',
      '0.29',
      '8',
      '5',
    ],
    [
      '114',
      'Schweri Kay',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '3',
      '3',
      '6',
      '0.33',
      '4',
      '0',
    ],
    [
      '113',
      'Pestoni Inti',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '3',
      '3',
      '6',
      '0.33',
      '6',
      '-3',
    ],
    [
      '112',
      'Petrini Patrick',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '12',
      '3',
      '3',
      '6',
      '0.50',
      '0',
      '-5',
    ],
    [
      '111',
      'Lhotak Lukas',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '4',
      '2',
      '6',
      '0.27',
      '6',
      '-3',
    ],
    [
      '110',
      'Schmutz Julian',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '5',
      '1',
      '6',
      '0.27',
      '18',
      '-3',
    ],
    [
      '109',
      'Senteler Sven',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '6',
      '0',
      '6',
      '0.30',
      '2',
      '0',
    ],
    [
      '108',
      'Nilsson Marcus',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '10',
      '0',
      '7',
      '7',
      '0.70',
      '4',
      '-4',
    ],
    [
      '107',
      'Grossmann Robin',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '1',
      '6',
      '7',
      '0.33',
      '4',
      '9',
    ],
    [
      '106',
      'Dünner Nico',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '23',
      '2',
      '5',
      '7',
      '0.30',
      '14',
      '-5',
    ],
    [
      '105',
      'Marti Christian',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '2',
      '5',
      '7',
      '0.37',
      '10',
      '6',
    ],
    [
      '104',
      'Jung Sven',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '3',
      '4',
      '7',
      '0.39',
      '4',
      '-2',
    ],
    [
      '103',
      'Klingberg Carl',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '3',
      '4',
      '7',
      '0.33',
      '32',
      '1',
    ],
    [
      '102',
      'Müller Marco',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '4',
      '3',
      '7',
      '0.41',
      '22',
      '-9',
    ],
    [
      '101',
      'Brunner Damien',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '8',
      '4',
      '3',
      '7',
      '0.88',
      '31',
      '1',
    ],
    [
      '100',
      'Bykov Andrey',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '5',
      '2',
      '7',
      '0.35',
      '2',
      '-4',
    ],
    [
      '99',
      'Rod Noah',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '6',
      '1',
      '7',
      '0.39',
      '4',
      '3',
    ],
    [
      '98',
      'Pettersson Fredrik',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '7',
      '0',
      '7',
      '0.41',
      '10',
      '-6',
    ],
    [
      '97',
      'Blaser Yannick',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '1',
      '7',
      '8',
      '0.40',
      '18',
      '3',
    ],
    [
      '96',
      'Novotny Jiri',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '1',
      '7',
      '8',
      '0.47',
      '8',
      '0',
    ],
    [
      '95',
      'Martschini Lino',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '1',
      '7',
      '8',
      '0.44',
      '10',
      '1',
    ],
    [
      '94',
      'Brannström Erik',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Verteidiger',
      '10',
      '2',
      '6',
      '8',
      '0.80',
      '6',
      '5',
    ],
    [
      '93',
      'Frick Lukas',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '2',
      '6',
      '8',
      '0.38',
      '4',
      '4',
    ],
    [
      '92',
      'Neukom Benjamin',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '3',
      '5',
      '8',
      '0.42',
      '14',
      '-2',
    ],
    [
      '91',
      'Künzle Mike',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '3',
      '5',
      '8',
      '0.40',
      '20',
      '1',
    ],
    [
      '90',
      'Hischier Luca',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '4',
      '4',
      '8',
      '0.40',
      '0',
      '-3',
    ],
    [
      '89',
      'Sprunger Julien',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '4',
      '4',
      '8',
      '0.38',
      '4',
      '-5',
    ],
    [
      '88',
      'Carr Daniel',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '8',
      '4',
      '4',
      '8',
      '1.00',
      '4',
      '5',
    ],
    [
      '87',
      'Praplan Vincent',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '4',
      '4',
      '8',
      '0.53',
      '31',
      '-8',
    ],
    [
      '86',
      'Turunen Teemu',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '4',
      '4',
      '8',
      '0.40',
      '6',
      '-8',
    ],
    [
      '85',
      'Haas Gaëtan',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '14',
      '5',
      '3',
      '8',
      '0.57',
      '4',
      '-4',
    ],
    [
      '84',
      'Eggenberger Nando',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '23',
      '6',
      '2',
      '8',
      '0.35',
      '8',
      '1',
    ],
    [
      '83',
      'Bürgler Dario',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '6',
      '2',
      '8',
      '0.44',
      '4',
      '-3',
    ],
    [
      '82',
      'Kurashev Philipp',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '13',
      '0',
      '9',
      '9',
      '0.69',
      '0',
      '1',
    ],
    [
      '81',
      'Hächler Cedric',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '1',
      '8',
      '9',
      '0.43',
      '14',
      '-6',
    ],
    [
      '80',
      'Blum Eric-Ray',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Verteidiger',
      '11',
      '1',
      '8',
      '9',
      '0.82',
      '6',
      '3',
    ],
    [
      '79',
      'Albrecht Yannick-Lennart',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '3',
      '6',
      '9',
      '0.43',
      '20',
      '6',
    ],
    [
      '78',
      'Geering Patrick',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '3',
      '6',
      '9',
      '0.45',
      '6',
      '8',
    ],
    [
      '77',
      'Wieser Marc',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '3',
      '6',
      '9',
      '0.41',
      '6',
      '0',
    ],
    [
      '76',
      'Jooris Josh',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '3',
      '6',
      '9',
      '0.60',
      '14',
      '-1',
    ],
    [
      '75',
      'Frehner Yannick',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '4',
      '5',
      '9',
      '0.43',
      '6',
      '6',
    ],
    [
      '74',
      'Schmutz Flavio',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '5',
      '4',
      '9',
      '0.41',
      '26',
      '-1',
    ],
    [
      '73',
      'Hügli Michael',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '5',
      '4',
      '9',
      '0.45',
      '4',
      '-10',
    ],
    [
      '72',
      'Heed Tim',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '6',
      '3',
      '9',
      '0.50',
      '6',
      '0',
    ],
    [
      '71',
      'Loeffel Romain',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Verteidiger',
      '16',
      '1',
      '9',
      '10',
      '0.62',
      '6',
      '2',
    ],
    [
      '70',
      'Winnik Daniel',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '2',
      '8',
      '10',
      '0.56',
      '10',
      '2',
    ],
    [
      '69',
      'Fora Michael',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '3',
      '7',
      '10',
      '0.48',
      '49',
      '-12',
    ],
    [
      '68',
      'Moy Tyler',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '3',
      '7',
      '10',
      '0.56',
      '6',
      '2',
    ],
    [
      '67',
      'Lehmann Marco',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '23',
      '4',
      '6',
      '10',
      '0.43',
      '8',
      '3',
    ],
    [
      '66',
      'Herren Yannick',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '4',
      '6',
      '10',
      '0.50',
      '31',
      '-10',
    ],
    [
      '65',
      'Fuchs Jason',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '4',
      '6',
      '10',
      '0.50',
      '16',
      '-2',
    ],
    [
      '64',
      'Rossi Matthias',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '5',
      '5',
      '10',
      '0.53',
      '6',
      '1',
    ],
    [
      '63',
      'Hudon Charles',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '13',
      '5',
      '5',
      '10',
      '0.77',
      '22',
      '7',
    ],
    [
      '62',
      'Bertaggia Alessio',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '5',
      '5',
      '10',
      '0.62',
      '8',
      '5',
    ],
    [
      '61',
      'Berger Pascal',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '6',
      '4',
      '10',
      '0.45',
      '18',
      '4',
    ],
    [
      '60',
      'Moses Steve',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '6',
      '4',
      '10',
      '0.62',
      '4',
      '-4',
    ],
    [
      '59',
      'Wick Jeremy',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '1',
      '10',
      '11',
      '0.52',
      '29',
      '-2',
    ],
    [
      '58',
      'Bodker Mikkel',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '2',
      '9',
      '11',
      '0.61',
      '0',
      '3',
    ],
    [
      '57',
      'Jeffrey Dustin',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '3',
      '8',
      '11',
      '0.61',
      '8',
      '-1',
    ],
    [
      '56',
      'Genazzi Joël',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '3',
      '8',
      '11',
      '0.52',
      '12',
      '8',
    ],
    [
      '55',
      'Egli Dominik',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '4',
      '7',
      '11',
      '0.55',
      '26',
      '-2',
    ],
    [
      '54',
      'Lindgren Perttu',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '4',
      '7',
      '11',
      '0.55',
      '8',
      '-13',
    ],
    [
      '53',
      'McLeod Ryan',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '4',
      '7',
      '11',
      '0.73',
      '10',
      '3',
    ],
    [
      '52',
      'Thornton Joe',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '12',
      '5',
      '6',
      '11',
      '0.92',
      '4',
      '0',
    ],
    [
      '51',
      'Herzog Fabrice',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '12',
      '5',
      '6',
      '11',
      '0.92',
      '16',
      '6',
    ],
    [
      '50',
      'Brithén Ted',
      { id: 102126, name: 'SC Bern', acronym: 'SCB', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '5',
      '6',
      '11',
      '0.65',
      '2',
      '-1',
    ],
    [
      '49',
      'Conacher Cory',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '6',
      '5',
      '11',
      '0.73',
      '18',
      '8',
    ],
    [
      '48',
      'Baltisberger Chris',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '9',
      '2',
      '11',
      '0.55',
      '28',
      '1',
    ],
    [
      '47',
      'Barberio Mark',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '1',
      '11',
      '12',
      '0.57',
      '12',
      '13',
    ],
    [
      '46',
      'Rathgeb Yannick',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '3',
      '9',
      '12',
      '0.60',
      '20',
      '-6',
    ],
    [
      '45',
      'Vermin Joël',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '5',
      '7',
      '12',
      '0.67',
      '8',
      '0',
    ],
    [
      '44',
      'Tömmernes Henrik',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Verteidiger',
      '18',
      '5',
      '7',
      '12',
      '0.67',
      '35',
      '2',
    ],
    [
      '43',
      'Zehnder Yannick',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '6',
      '6',
      '12',
      '0.60',
      '6',
      '9',
    ],
    [
      '42',
      'Fazzini Luca',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '8',
      '4',
      '12',
      '0.67',
      '10',
      '1',
    ],
    [
      '41',
      'Desharnais David',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '3',
      '10',
      '13',
      '0.76',
      '6',
      '1',
    ],
    [
      '40',
      'Baumgartner Benjamin',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '4',
      '9',
      '13',
      '0.62',
      '6',
      '1',
    ],
    [
      '39',
      'Profico Leandro',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Verteidiger',
      '19',
      '4',
      '9',
      '13',
      '0.68',
      '4',
      '0',
    ],
    [
      '38',
      'Pouliot Marc-Antoine',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '17',
      '6',
      '7',
      '13',
      '0.76',
      '18',
      '-4',
    ],
    [
      '37',
      'Bertschy Christoph',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '8',
      '5',
      '13',
      '0.62',
      '14',
      '6',
    ],
    [
      '36',
      'Rajala Toni',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '5',
      '9',
      '14',
      '0.70',
      '16',
      '-9',
    ],
    [
      '35',
      'Palushaj Aaron',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '15',
      '5',
      '9',
      '14',
      '0.93',
      '6',
      '-8',
    ],
    [
      '34',
      'Krüger Marcus',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '5',
      '9',
      '14',
      '0.74',
      '10',
      '-1',
    ],
    [
      '33',
      'Nygren Magnus',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Verteidiger',
      '22',
      '8',
      '6',
      '14',
      '0.64',
      '20',
      '1',
    ],
    [
      '32',
      'Kenins Ronalds',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '3',
      '12',
      '15',
      '0.71',
      '14',
      '6',
    ],
    [
      '31',
      'Diaz Raphael',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '4',
      '11',
      '15',
      '0.71',
      '8',
      '14',
    ],
    [
      '30',
      'Rowe Andrew',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '5',
      '10',
      '15',
      '0.68',
      '20',
      '-1',
    ],
    [
      '29',
      'Maxwell Ben',
      { id: 102127, name: 'SCL Tigers', acronym: 'SCL', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '7',
      '8',
      '15',
      '0.68',
      '6',
      '-2',
    ],
    [
      '28',
      'Fehr Eric',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '10',
      '5',
      '15',
      '0.83',
      '38',
      '4',
    ],
    [
      '27',
      'Alatalo Santeri',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '3',
      '13',
      '16',
      '0.76',
      '14',
      '1',
    ],
    [
      '26',
      'Riat Damien',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '5',
      '11',
      '16',
      '0.89',
      '4',
      '2',
    ],
    [
      '25',
      'Flynn Brian',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '6',
      '10',
      '16',
      '0.73',
      '17',
      '-7',
    ],
    [
      '24',
      'Clark Kevin',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '23',
      '7',
      '9',
      '16',
      '0.70',
      '22',
      '4',
    ],
    [
      '23',
      'Noreau Maxim',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '1',
      '16',
      '17',
      '0.85',
      '4',
      '6',
    ],
    [
      '22',
      'Moser Janis Jérôme',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Verteidiger',
      '20',
      '4',
      '13',
      '17',
      '0.85',
      '4',
      '4',
    ],
    [
      '21',
      'Hofer Fabio',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '8',
      '9',
      '17',
      '0.85',
      '4',
      '-1',
    ],
    [
      '20',
      'Simion Dario',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '11',
      '6',
      '17',
      '0.89',
      '0',
      '6',
    ],
    [
      '19',
      'DiDomenico Christopher',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '3',
      '15',
      '18',
      '1.00',
      '8',
      '-6',
    ],
    [
      '18',
      'Corvi Enzo',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '3',
      '15',
      '18',
      '0.90',
      '8',
      '-2',
    ],
    [
      '17',
      'Arcobello Mark',
      { id: 101150, name: 'HC Lugano', acronym: 'HCL', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '4',
      '14',
      '18',
      '1.00',
      '26',
      '9',
    ],
    [
      '16',
      'Roe Garrett',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '5',
      '13',
      '18',
      '0.95',
      '38',
      '4',
    ],
    [
      '15',
      'Andrighetto Sven',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '6',
      '12',
      '18',
      '0.90',
      '6',
      '4',
    ],
    [
      '14',
      'Cunti Luca',
      { id: 102128, name: 'EHC Biel-Bienne', acronym: 'EHCB', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '7',
      '11',
      '18',
      '0.90',
      '10',
      '1',
    ],
    [
      '13',
      'Mottet Killian',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '12',
      '6',
      '18',
      '0.86',
      '8',
      '5',
    ],
    [
      '12',
      'Gunderson Ryan',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Verteidiger',
      '21',
      '6',
      '13',
      '19',
      '0.90',
      '6',
      '6',
    ],
    [
      '11',
      'Gibbons Brian',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '7',
      '12',
      '19',
      '0.90',
      '20',
      '17',
    ],
    [
      '10',
      'Stalberg Viktor',
      { id: 103138, name: 'Fribourg-Gottéron', acronym: 'FRI', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '8',
      '11',
      '19',
      '1.06',
      '6',
      '10',
    ],
    [
      '9',
      'Ambühl Andres',
      { id: 101151, name: 'HC Davos', acronym: 'HCD', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '10',
      '9',
      '19',
      '0.86',
      '12',
      '-4',
    ],
    [
      '8',
      'Hofmann Gregory',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '8',
      '12',
      '20',
      '1.05',
      '12',
      '4',
    ],
    [
      '7',
      'Nättinen Julius',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '16',
      '14',
      '6',
      '20',
      '1.25',
      '0',
      '-2',
    ],
    [
      '6',
      'Malgin Denis',
      { id: 103141, name: 'Lausanne HC', acronym: 'LHC', signed: false, type: 'team' },
      'Stürmer',
      '19',
      '11',
      '10',
      '21',
      '1.11',
      '12',
      '17',
    ],
    [
      '5',
      'Zwerger Dominic',
      { id: 101152, name: 'HC Ambri-Piotta', acronym: 'HCAP', signed: false, type: 'team' },
      'Stürmer',
      '22',
      '5',
      '17',
      '22',
      '1.00',
      '8',
      '-9',
    ],
    [
      '4',
      'Kovar Jan',
      { id: 101144, name: 'EV Zug', acronym: 'EVZ', signed: false, type: 'team' },
      'Stürmer',
      '21',
      '7',
      '15',
      '22',
      '1.05',
      '30',
      '12',
    ],
    [
      '3',
      'Hollenstein Denis',
      { id: 101139, name: 'ZSC Lions', acronym: 'ZSC', signed: false, type: 'team' },
      'Stürmer',
      '20',
      '13',
      '9',
      '22',
      '1.10',
      '12',
      '2',
    ],
    [
      '2',
      'Cervenka Roman',
      { id: 101060, name: 'SC Rapperswil-Jona Lakers', acronym: 'SCRJ', signed: false, type: 'team' },
      'Stürmer',
      '23',
      '8',
      '16',
      '24',
      '1.04',
      '22',
      '3',
    ],
    [
      '1',
      'Omark Linus',
      { id: 103140, name: 'Genève-Servette HC', acronym: 'GSHC', signed: false, type: 'team' },
      'Stürmer',
      '18',
      '8',
      '17',
      '25',
      '1.39',
      '10',
      '3',
    ],
  ],
  alias: 'player',
}

module.exports = response
