module.exports = {
  SiteKit: {
    Parameters: {
      feed: 'modulekit',
      view: 'player',
      key: '2976319eb44abe94',
      fmt: 'json',
      client_code: 'ohl',
      lang: 'en',
      player_id: '7662',
      category: 'seasonstats',
      lang_id: 1,
      league_id: '1',
      season_id: '68',
    },
    Player: {
      regular: [
        {
          season_id: '68',
          season_name: '2019-20 Regular Season',
          shortname: '2019-20 Reg.',
          playoff: '0',
          career: '1',
          max_start_date: '2019-09-17',
          jersey_number: '16',
          goals: '55',
          games_played: '46',
          assists: '31',
          points: '86',
          plus_minus: '29',
          penalty_minutes: '40',
          power_play_goals: '13',
          power_play_assists: '15',
          shots: '255',
          shootout_attempts: '1',
          shootout_goals: '1',
          shootout_percentage: '100.0',
          shooting_percentage: '21.6',
          shootout_winning_goals: '0',
          points_per_game: '1.87',
          short_handed_goals: '8',
          short_handed_assists: '1',
          game_winning_goals: '10',
          game_tieing_goals: '0',
          faceoff_wins: '10',
          faceoff_attempts: '25',
          faceoff_pct: '40.0',
          hits: '0',
          shots_on: '130',
          shots_wide: '125',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '4',
          insurance_goals: '7',
          overtime_goals: '0',
          unassisted_goals: '8',
          empty_net_goals: '3',
          penalty_minutes_per_game: '0.869565',
        },
        {
          season_id: '63',
          season_name: '2018-19 Regular Season',
          shortname: '2018-19 Reg.',
          playoff: '0',
          career: '1',
          max_start_date: '2018-09-17',
          jersey_number: '16',
          goals: '-',
          games_played: '-',
          assists: '-',
          points: '-',
          plus_minus: '-3',
          penalty_minutes: '-',
          power_play_goals: '8',
          power_play_assists: '11',
          shots: '-',
          shootout_attempts: '4',
          shootout_goals: '2',
          shootout_percentage: '50.0',
          shooting_percentage: '14.6',
          shootout_winning_goals: '1',
          points_per_game: '1.02',
          short_handed_goals: '1',
          short_handed_assists: '1',
          game_winning_goals: '3',
          game_tieing_goals: '0',
          faceoff_wins: '17',
          faceoff_attempts: '37',
          faceoff_pct: '45.9',
          hits: '0',
          shots_on: '105',
          shots_wide: '80',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '5',
          insurance_goals: '1',
          overtime_goals: '1',
          unassisted_goals: '4',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.444444',
        },
        {
          season_id: '60',
          season_name: '2017-18 Regular Season',
          shortname: '2017-18 Reg.',
          playoff: '0',
          career: '1',
          max_start_date: '2017-09-18',
          jersey_number: '16',
          goals: '15',
          games_played: '62',
          assists: '18',
          points: '33',
          plus_minus: '-27',
          penalty_minutes: '14',
          power_play_goals: '5',
          power_play_assists: '6',
          shots: '115',
          shootout_attempts: '2',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '13.0',
          shootout_winning_goals: '0',
          points_per_game: '0.53',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '1',
          game_tieing_goals: '0',
          faceoff_wins: '166',
          faceoff_attempts: '385',
          faceoff_pct: '43.1',
          hits: '0',
          shots_on: '70',
          shots_wide: '45',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '2',
          insurance_goals: '1',
          overtime_goals: '0',
          unassisted_goals: '1',
          empty_net_goals: '1',
          penalty_minutes_per_game: '0.225806',
        },
        {
          season_name: 'total',
          shortname: 'total',
          playoff: 0,
          season_id: 191,
          career: 3,
          max_start_date: 6054,
          jersey_number: 48,
          goals: 97,
          games_played: 162,
          assists: 77,
          points: 174,
          plus_minus: -1,
          penalty_minutes: 78,
          power_play_goals: 26,
          power_play_assists: 32,
          shots: 555,
          shootout_attempts: 7,
          shootout_goals: 3,
          shootout_percentage: '42.9',
          shooting_percentage: '17.5',
          shootout_winning_goals: 1,
          points_per_game: '1.07',
          short_handed_goals: 9,
          short_handed_assists: 2,
          game_winning_goals: 14,
          game_tieing_goals: 0,
          faceoff_wins: 193,
          faceoff_attempts: 447,
          faceoff_pct: 129,
          hits: 0,
          shots_on: 305,
          shots_wide: 250,
          first_goals: 11,
          insurance_goals: 9,
          overtime_goals: 1,
          unassisted_goals: 13,
          empty_net_goals: 4,
          penalty_minutes_per_game: '0.48',
        },
      ],
      exhibition: [
        {
          season_id: '67',
          season_name: '2019 Pre-season',
          shortname: '19 Preseason',
          playoff: '0',
          career: '0',
          max_start_date: '2019-08-01',
          jersey_number: '16',
          goals: '3',
          games_played: '1',
          assists: '0',
          points: '3',
          plus_minus: '2',
          penalty_minutes: '0',
          power_play_goals: '0',
          power_play_assists: '0',
          shots: '4',
          shootout_attempts: '0',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '75.0',
          shootout_winning_goals: '0',
          points_per_game: '3.00',
          short_handed_goals: '1',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '0',
          faceoff_pct: '0.0',
          hits: '0',
          shots_on: '2',
          shots_wide: '2',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '0',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '1',
          empty_net_goals: '1',
          penalty_minutes_per_game: '0.000000',
        },
        {
          season_id: '62',
          season_name: '2018 Pre-season',
          shortname: '18 Preseason',
          playoff: '0',
          career: '0',
          max_start_date: '2018-08-01',
          jersey_number: '16',
          goals: '1',
          games_played: '5',
          assists: '4',
          points: '5',
          plus_minus: '-2',
          penalty_minutes: '6',
          power_play_goals: '1',
          power_play_assists: '3',
          shots: '26',
          shootout_attempts: '2',
          shootout_goals: '1',
          shootout_percentage: '50.0',
          shooting_percentage: '3.8',
          shootout_winning_goals: '0',
          points_per_game: '1.00',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '16',
          faceoff_attempts: '28',
          faceoff_pct: '57.1',
          hits: '0',
          shots_on: '13',
          shots_wide: '13',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '0',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '1.200000',
        },
        {
          season_id: '59',
          season_name: '2017 Pre-season',
          shortname: '17 Preseason',
          playoff: '0',
          career: '0',
          max_start_date: '2017-08-22',
          jersey_number: '16',
          goals: '3',
          games_played: '6',
          assists: '0',
          points: '3',
          plus_minus: '5',
          penalty_minutes: '10',
          power_play_goals: '0',
          power_play_assists: '0',
          shots: '13',
          shootout_attempts: '1',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '23.1',
          shootout_winning_goals: '0',
          points_per_game: '0.50',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '33',
          faceoff_attempts: '75',
          faceoff_pct: '44.0',
          hits: '0',
          shots_on: '9',
          shots_wide: '4',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '0',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '1.666667',
        },
        {
          season_name: 'total',
          shortname: 'total',
          playoff: 0,
          season_id: 188,
          career: 0,
          max_start_date: 6054,
          jersey_number: 48,
          goals: 7,
          games_played: 12,
          assists: 4,
          points: 11,
          plus_minus: 5,
          penalty_minutes: 16,
          power_play_goals: 1,
          power_play_assists: 3,
          shots: 43,
          shootout_attempts: 3,
          shootout_goals: 1,
          shootout_percentage: '33.3',
          shooting_percentage: '16.3',
          shootout_winning_goals: 0,
          points_per_game: '0.92',
          short_handed_goals: 1,
          short_handed_assists: 0,
          game_winning_goals: 0,
          game_tieing_goals: 0,
          faceoff_wins: 49,
          faceoff_attempts: 103,
          faceoff_pct: 101.1,
          hits: 0,
          shots_on: 24,
          shots_wide: 19,
          first_goals: 0,
          insurance_goals: 0,
          overtime_goals: 0,
          unassisted_goals: 1,
          empty_net_goals: 1,
          penalty_minutes_per_game: '1.33',
        },
      ],
      playoff: [
        {
          season_id: '66',
          season_name: '2019 Playoffs',
          shortname: '19 Playoffs',
          playoff: '1',
          career: '1',
          max_start_date: '2019-03-19',
          jersey_number: '16',
          goals: '1',
          games_played: '5',
          assists: '1',
          points: '2',
          plus_minus: '-7',
          penalty_minutes: '2',
          power_play_goals: '1',
          power_play_assists: '0',
          shots: '16',
          shootout_attempts: '0',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '6.3',
          shootout_winning_goals: '0',
          points_per_game: '0.40',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '4',
          faceoff_pct: '0.0',
          hits: '0',
          shots_on: '12',
          shots_wide: '4',
          team_name: 'Peterborough Petes',
          team_code: 'PBO',
          team_city: 'Peterborough',
          team_nickname: 'Petes',
          team_id: '6',
          active: '1',
          first_goals: '0',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.400000',
        },
        {
          season_name: 'total',
          shortname: 'total',
          playoff: 1,
          season_id: 66,
          career: 1,
          max_start_date: 2019,
          jersey_number: 16,
          goals: 1,
          games_played: 5,
          assists: 1,
          points: 2,
          plus_minus: -7,
          penalty_minutes: 2,
          power_play_goals: 1,
          power_play_assists: 0,
          shots: 16,
          shootout_attempts: 0,
          shootout_goals: 0,
          shootout_percentage: '0.0',
          shooting_percentage: '6.2',
          shootout_winning_goals: 0,
          points_per_game: '0.40',
          short_handed_goals: 0,
          short_handed_assists: 0,
          game_winning_goals: 0,
          game_tieing_goals: 0,
          faceoff_wins: 0,
          faceoff_attempts: 4,
          faceoff_pct: 0,
          hits: 0,
          shots_on: 12,
          shots_wide: 4,
          first_goals: 0,
          insurance_goals: 0,
          overtime_goals: 0,
          unassisted_goals: 0,
          empty_net_goals: 0,
          penalty_minutes_per_game: '0.40',
        },
      ],
    },
    Copyright: {
      required_copyright: 'Official statistics provided by Ontario Hockey League',
      required_link: 'http://leaguestat.com',
      powered_by: 'Powered by HockeyTech.com',
      powered_by_url: 'http://hockeytech.com',
    },
  },
}
