module.exports = {
  SiteKit: {
    Parameters: {
      feed: 'modulekit',
      view: 'player',
      key: '41b145a848f4bd67',
      fmt: 'json',
      client_code: 'whl',
      lang: 'en',
      player_id: '27960',
      category: 'seasonstats',
      lang_id: 1,
      league_id: '26',
      season_id: '270',
    },
    Player: {
      regular: [
        {
          season_id: '270',
          season_name: '2019 - 20 Regular Season',
          shortname: '19 - 20 Reg',
          playoff: '0',
          career: '1',
          max_start_date: '2019-09-20',
          jersey_number: '18',
          goals: '12',
          games_played: '53',
          assists: '37',
          points: '49',
          plus_minus: '18',
          penalty_minutes: '8',
          power_play_goals: '3',
          power_play_assists: '14',
          shots: '129',
          shootout_attempts: '0',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '9.3',
          shootout_winning_goals: '0',
          points_per_game: '0.92',
          short_handed_goals: '0',
          short_handed_assists: '1',
          game_winning_goals: '4',
          game_tieing_goals: '0',
          faceoff_wins: '1',
          faceoff_attempts: '1',
          faceoff_pct: '100.0',
          hits: '0',
          team_name: 'Spokane Chiefs',
          team_code: 'SPO',
          team_city: 'Spokane',
          team_nickname: 'Chiefs',
          team_id: '215',
          active: '1',
          first_goals: '3',
          insurance_goals: '0',
          overtime_goals: '1',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.150943',
        },
        {
          season_id: '266',
          season_name: '2018 - 19 Regular Season',
          shortname: '18 - 19 Reg',
          playoff: '0',
          career: '1',
          max_start_date: '2018-09-21',
          jersey_number: '18',
          goals: '-',
          games_played: '-',
          assists: '-',
          points: '-',
          plus_minus: '17',
          penalty_minutes: '14',
          power_play_goals: '3',
          power_play_assists: '11',
          shots: '-',
          shootout_attempts: '1',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '9.2',
          shootout_winning_goals: '0',
          points_per_game: '0.77',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '2',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '0',
          faceoff_pct: '0.0',
          hits: '0',
          team_name: 'Spokane Chiefs',
          team_code: 'SPO',
          team_city: 'Spokane',
          team_nickname: 'Chiefs',
          team_id: '215',
          active: '1',
          first_goals: '1',
          insurance_goals: '1',
          overtime_goals: '0',
          unassisted_goals: '2',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.297872',
        },
        {
          season_id: '262',
          season_name: '2017 - 18 Regular Season',
          shortname: '17 - 18 Reg',
          playoff: '0',
          career: '1',
          max_start_date: '2017-10-13',
          jersey_number: '18',
          goals: '9',
          games_played: '54',
          assists: '26',
          points: '35',
          plus_minus: '9',
          penalty_minutes: '24',
          power_play_goals: '1',
          power_play_assists: '9',
          shots: '91',
          shootout_attempts: '1',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '9.9',
          shootout_winning_goals: '0',
          points_per_game: '0.65',
          short_handed_goals: '1',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '1',
          faceoff_pct: '0.0',
          hits: '0',
          team_name: 'Spokane Chiefs',
          team_code: 'SPO',
          team_city: 'Spokane',
          team_nickname: 'Chiefs',
          team_id: '215',
          active: '1',
          first_goals: '1',
          insurance_goals: '2',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.444444',
        },
        {
          season_name: 'total',
          shortname: 'total',
          playoff: 0,
          season_id: 798,
          career: 3,
          max_start_date: 6054,
          jersey_number: 54,
          goals: 31,
          games_played: 154,
          assists: 89,
          points: 120,
          plus_minus: 44,
          penalty_minutes: 46,
          power_play_goals: 7,
          power_play_assists: 34,
          shots: 329,
          shootout_attempts: 2,
          shootout_goals: 0,
          shootout_percentage: '0.0',
          shooting_percentage: '9.4',
          shootout_winning_goals: 0,
          points_per_game: '0.78',
          short_handed_goals: 1,
          short_handed_assists: 1,
          game_winning_goals: 6,
          game_tieing_goals: 0,
          faceoff_wins: 1,
          faceoff_attempts: 2,
          faceoff_pct: 100,
          hits: 0,
          first_goals: 5,
          insurance_goals: 3,
          overtime_goals: 1,
          unassisted_goals: 2,
          empty_net_goals: 0,
          penalty_minutes_per_game: '0.30',
        },
      ],
      exhibition: [
        {
          season_id: '269',
          season_name: '2019 Pre Season',
          shortname: '2019 Pre',
          playoff: '0',
          career: '0',
          max_start_date: '2019-08-27',
          jersey_number: '18',
          goals: '1',
          games_played: '2',
          assists: '1',
          points: '2',
          plus_minus: '-4',
          penalty_minutes: '0',
          power_play_goals: '1',
          power_play_assists: '1',
          shots: '1',
          shootout_attempts: '1',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '100.0',
          shootout_winning_goals: '0',
          points_per_game: '1.00',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '0',
          faceoff_pct: '0.0',
          hits: '0',
          team_name: 'Spokane Chiefs',
          team_code: 'SPO',
          team_city: 'Spokane',
          team_nickname: 'Chiefs',
          team_id: '215',
          active: '1',
          first_goals: '1',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.000000',
        },
        {
          season_name: 'total',
          shortname: 'total',
          playoff: 0,
          season_id: 269,
          career: 0,
          max_start_date: 2019,
          jersey_number: 18,
          goals: 1,
          games_played: 2,
          assists: 1,
          points: 2,
          plus_minus: -4,
          penalty_minutes: 0,
          power_play_goals: 1,
          power_play_assists: 1,
          shots: 1,
          shootout_attempts: 1,
          shootout_goals: 0,
          shootout_percentage: '0.0',
          shooting_percentage: '100.0',
          shootout_winning_goals: 0,
          points_per_game: '1.00',
          short_handed_goals: 0,
          short_handed_assists: 0,
          game_winning_goals: 0,
          game_tieing_goals: 0,
          faceoff_wins: 0,
          faceoff_attempts: 0,
          faceoff_pct: 0,
          hits: 0,
          first_goals: 1,
          insurance_goals: 0,
          overtime_goals: 0,
          unassisted_goals: 0,
          empty_net_goals: 0,
          penalty_minutes_per_game: '0.00',
        },
      ],
      playoff: [
        {
          season_id: '267',
          season_name: '2019 WHL Playoffs',
          shortname: '19 Playoffs',
          playoff: '1',
          career: '1',
          max_start_date: '2019-03-22',
          jersey_number: '18',
          goals: '0',
          games_played: '12',
          assists: '2',
          points: '2',
          plus_minus: '3',
          penalty_minutes: '4',
          power_play_goals: '0',
          power_play_assists: '1',
          shots: '17',
          shootout_attempts: '0',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '0.0',
          shootout_winning_goals: '0',
          points_per_game: '0.17',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '0',
          faceoff_pct: '0.0',
          hits: '0',
          team_name: 'Spokane Chiefs',
          team_code: 'SPO',
          team_city: 'Spokane',
          team_nickname: 'Chiefs',
          team_id: '215',
          active: '1',
          first_goals: '0',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.333333',
        },
        {
          season_id: '264',
          season_name: '2018 WHL Playoffs',
          shortname: '18 Playoffs',
          playoff: '1',
          career: '1',
          max_start_date: '2018-03-22',
          jersey_number: '18',
          goals: '0',
          games_played: '5',
          assists: '0',
          points: '0',
          plus_minus: '-1',
          penalty_minutes: '0',
          power_play_goals: '0',
          power_play_assists: '0',
          shots: '4',
          shootout_attempts: '0',
          shootout_goals: '0',
          shootout_percentage: '0.0',
          shooting_percentage: '0.0',
          shootout_winning_goals: '0',
          points_per_game: '0.00',
          short_handed_goals: '0',
          short_handed_assists: '0',
          game_winning_goals: '0',
          game_tieing_goals: '0',
          faceoff_wins: '0',
          faceoff_attempts: '0',
          faceoff_pct: '0.0',
          hits: '0',
          team_name: 'Spokane Chiefs',
          team_code: 'SPO',
          team_city: 'Spokane',
          team_nickname: 'Chiefs',
          team_id: '215',
          active: '1',
          first_goals: '0',
          insurance_goals: '0',
          overtime_goals: '0',
          unassisted_goals: '0',
          empty_net_goals: '0',
          penalty_minutes_per_game: '0.000000',
        },
        {
          season_name: 'total',
          shortname: 'total',
          playoff: 1,
          season_id: 531,
          career: 2,
          max_start_date: 4037,
          jersey_number: 36,
          goals: 0,
          games_played: 17,
          assists: 2,
          points: 2,
          plus_minus: 2,
          penalty_minutes: 4,
          power_play_goals: 0,
          power_play_assists: 1,
          shots: 21,
          shootout_attempts: 0,
          shootout_goals: 0,
          shootout_percentage: '0.0',
          shooting_percentage: '0.0',
          shootout_winning_goals: 0,
          points_per_game: '0.12',
          short_handed_goals: 0,
          short_handed_assists: 0,
          game_winning_goals: 0,
          game_tieing_goals: 0,
          faceoff_wins: 0,
          faceoff_attempts: 0,
          faceoff_pct: 0,
          hits: 0,
          first_goals: 0,
          insurance_goals: 0,
          overtime_goals: 0,
          unassisted_goals: 0,
          empty_net_goals: 0,
          penalty_minutes_per_game: '0.24',
        },
      ],
    },
    Copyright: {
      required_copyright: 'Official statistics provided by Western Hockey League',
      required_link: 'http://leaguestat.com',
      powered_by: 'Powered by HockeyTech.com',
      powered_by_url: 'http://hockeytech.com',
    },
  },
}
