module.exports = {
  _type: 'Corebine.Core.Protocol.Response.Object',
  data: {
    _type: 'Corebine.Core.Sport.Match',
    _entityId: '726aeb7bddff5b8567b9230d',
    externalId: '18153',
    externalSource: 'hockeyTech',
    startDate: '2021-01-02T01:05:00.000Z',
    venue: { _type: 'Corebine.Core.Sport.Arena', _entityId: '560dfc549f8c7e516af284ef', name: 'INTRUST Bank Arena' },
    teams: {
      home: {
        _type: 'Corebine.Core.Sport.Team',
        _entityId: '31ffb756ae0a30e567dcf226',
        externalId: '72',
        name: 'Wichita Thunder',
        shortName: 'WIC',
        link: {
          _type: 'Corebine.Core.Type.Link.ClientSpecific',
          clients: { echl: { _type: 'Corebine.Core.Type.Link.Internal', pageEntityId: '1', url: '/teams/wichita-thunder' } },
        },
        logo: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/logos/72.png' },
        athletes: [
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'fd5b0585aaa605917c69a0be',
            externalId: '7018',
            firstName: 'Mitch',
            lastName: 'Gillam',
            number: 37,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Goalie',
              shortName: 'G',
              category: 'Goalies',
              order: 6,
              categoryOrder: 3,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7018.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'fd5b0585aaa605917c69a0be', firstName: 'Mitch', lastName: 'Gillam' },
              query: 'player-fd5b0585aaa605917c69a0be.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Saves', shortName: 'SV', value: 29 },
                {
                  _type: 'Corebine.Core.Type.Property.Number',
                  name: 'Save Percentage',
                  shortName: 'SV%',
                  value: 85.29411764705883,
                  units: 'percents',
                  precision: 3,
                },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals Against', shortName: 'GA', value: 5 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '56c30d1c3fae5dd3314e36aa',
            externalId: '8035',
            firstName: 'Evan',
            lastName: 'Weninger',
            number: 40,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Goalie',
              shortName: 'G',
              category: 'Goalies',
              order: 6,
              categoryOrder: 3,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8035.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '56c30d1c3fae5dd3314e36aa', firstName: 'Evan', lastName: 'Weninger' },
              query: 'player-56c30d1c3fae5dd3314e36aa.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Saves', shortName: 'SV', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Number', name: 'Save Percentage', shortName: 'SV%', value: 0, units: 'percents', precision: 3 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals Against', shortName: 'GA', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '829903aaa0df9e459370946b',
            externalId: '8262',
            firstName: 'Sean',
            lastName: 'Allen',
            number: 2,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8262.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '829903aaa0df9e459370946b', firstName: 'Sean', lastName: 'Allen' },
              query: 'player-829903aaa0df9e459370946b.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -3 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '6703b9d7fecaadcf36c31ba0',
            externalId: '8264',
            firstName: 'Patrik',
            lastName: 'Parkkonen',
            number: 3,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8264.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '6703b9d7fecaadcf36c31ba0', firstName: 'Patrik', lastName: 'Parkkonen' },
              query: 'player-6703b9d7fecaadcf36c31ba0.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '3de991e58ca9e9f70aace60f',
            externalId: '8581',
            firstName: 'Alex',
            lastName: 'Berardinelli',
            number: 7,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8581.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '3de991e58ca9e9f70aace60f', firstName: 'Alex', lastName: 'Berardinelli' },
              query: 'player-3de991e58ca9e9f70aace60f.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '53cbb237461f4a8e2688c515',
            externalId: '8434',
            firstName: 'Cam',
            lastName: 'Clarke',
            number: 12,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8434.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '53cbb237461f4a8e2688c515', firstName: 'Cam', lastName: 'Clarke' },
              query: 'player-53cbb237461f4a8e2688c515.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'a6ab7f0d8a0a71ff907a1075',
            externalId: '8602',
            firstName: 'Gordie',
            lastName: 'Green',
            number: 18,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8602.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'a6ab7f0d8a0a71ff907a1075', firstName: 'Gordie', lastName: 'Green' },
              query: 'player-a6ab7f0d8a0a71ff907a1075.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'f11790b2c03184166f661426',
            externalId: '8585',
            firstName: 'Chantz',
            lastName: 'Petruic',
            number: 19,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8585.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'f11790b2c03184166f661426', firstName: 'Chantz', lastName: 'Petruic' },
              query: 'player-f11790b2c03184166f661426.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'a0909c98882324416ddb48c6',
            externalId: '6877',
            firstName: 'Jacob',
            lastName: 'Graves',
            number: 20,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/6877.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'a0909c98882324416ddb48c6', firstName: 'Jacob', lastName: 'Graves' },
              query: 'player-a0909c98882324416ddb48c6.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '52739ea0b495473cd1660f68',
            externalId: '7978',
            firstName: 'Jay',
            lastName: 'Dickman',
            number: 21,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7978.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '52739ea0b495473cd1660f68', firstName: 'Jay', lastName: 'Dickman' },
              query: 'player-52739ea0b495473cd1660f68.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'b58cfceefa1d5b79ff030dc1',
            externalId: '8261',
            firstName: 'Beau',
            lastName: 'Starrett',
            number: 22,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8261.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'b58cfceefa1d5b79ff030dc1', firstName: 'Beau', lastName: 'Starrett' },
              query: 'player-b58cfceefa1d5b79ff030dc1.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'a29bdc12c794fe8f176c80a1',
            externalId: '8352',
            firstName: 'Vincent',
            lastName: 'Desharnais',
            number: 23,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8352.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'a29bdc12c794fe8f176c80a1', firstName: 'Vincent', lastName: 'Desharnais' },
              query: 'player-a29bdc12c794fe8f176c80a1.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'bebd73ff78bc702709fd4073',
            externalId: '8601',
            firstName: 'Bobby',
            lastName: 'McMann',
            number: 24,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8601.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'bebd73ff78bc702709fd4073', firstName: 'Bobby', lastName: 'McMann' },
              query: 'player-bebd73ff78bc702709fd4073.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '84d49ba9c6e567ac2225514d',
            externalId: '8586',
            firstName: 'Brayden',
            lastName: 'Watts',
            number: 29,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8586.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '84d49ba9c6e567ac2225514d', firstName: 'Brayden', lastName: 'Watts' },
              query: 'player-84d49ba9c6e567ac2225514d.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '54e1e1664895f0626b635787',
            externalId: '8359',
            firstName: 'Matteo',
            lastName: 'Gennaro',
            number: 34,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8359.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '54e1e1664895f0626b635787', firstName: 'Matteo', lastName: 'Gennaro' },
              query: 'player-54e1e1664895f0626b635787.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 3 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '18f14e2638bd2b7004fa9df8',
            externalId: '8599',
            firstName: 'Jeremy',
            lastName: 'McKenna',
            number: 41,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8599.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '18f14e2638bd2b7004fa9df8', firstName: 'Jeremy', lastName: 'McKenna' },
              query: 'player-18f14e2638bd2b7004fa9df8.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '03259f48d2f1564cbd772e41',
            externalId: '7477',
            firstName: 'Spencer',
            lastName: 'Dorowicz',
            number: 51,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7477.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '03259f48d2f1564cbd772e41', firstName: 'Spencer', lastName: 'Dorowicz' },
              query: 'player-03259f48d2f1564cbd772e41.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '878ece257ab3331aedfd3850',
            externalId: '8256',
            firstName: 'Peter',
            lastName: 'Crinella',
            number: 72,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8256.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '878ece257ab3331aedfd3850', firstName: 'Peter', lastName: 'Crinella' },
              query: 'player-878ece257ab3331aedfd3850.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '009ae28b6a3cb7d8136579be',
            externalId: '4741',
            firstName: 'Mathieu',
            lastName: 'Gagnon',
            number: 75,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/4741.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '009ae28b6a3cb7d8136579be', firstName: 'Mathieu', lastName: 'Gagnon' },
              query: 'player-009ae28b6a3cb7d8136579be.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '52f9605ddd1c13aaf01d9994',
            externalId: '6458',
            firstName: 'Anthony',
            lastName: 'Beauregard',
            number: 91,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/6458.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '52f9605ddd1c13aaf01d9994', firstName: 'Anthony', lastName: 'Beauregard' },
              query: 'player-52f9605ddd1c13aaf01d9994.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 3 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
        ],
      },
      away: {
        _type: 'Corebine.Core.Sport.Team',
        _entityId: '5c5c2fc55ce4ceb584def768',
        externalId: '66',
        name: 'Allen Americans',
        shortName: 'ALN',
        link: {
          _type: 'Corebine.Core.Type.Link.ClientSpecific',
          clients: { echl: { _type: 'Corebine.Core.Type.Link.Internal', pageEntityId: '1', url: '/teams/allen-americans' } },
        },
        logo: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/logos/66.png' },
        athletes: [
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '11867f754e8723d85094bf5e',
            externalId: '6814',
            firstName: 'Thomas',
            lastName: 'Hodges',
            number: 32,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Goalie',
              shortName: 'G',
              category: 'Goalies',
              order: 6,
              categoryOrder: 3,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/6814.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '11867f754e8723d85094bf5e', firstName: 'Thomas', lastName: 'Hodges' },
              query: 'player-11867f754e8723d85094bf5e.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Saves', shortName: 'SV', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Number', name: 'Save Percentage', shortName: 'SV%', value: 0, units: 'percents', precision: 3 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals Against', shortName: 'GA', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '46d3accfab403677c306cf35',
            externalId: '8209',
            firstName: 'Zach',
            lastName: 'Sawchenko',
            number: 34,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Goalie',
              shortName: 'G',
              category: 'Goalies',
              order: 6,
              categoryOrder: 3,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8209.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '46d3accfab403677c306cf35', firstName: 'Zach', lastName: 'Sawchenko' },
              query: 'player-46d3accfab403677c306cf35.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Saves', shortName: 'SV', value: 11 },
                {
                  _type: 'Corebine.Core.Type.Property.Number',
                  name: 'Save Percentage',
                  shortName: 'SV%',
                  value: 91.66666666666667,
                  units: 'percents',
                  precision: 3,
                },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals Against', shortName: 'GA', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '5bd638a01be89cc3172095a7',
            externalId: '7804',
            firstName: 'Turner',
            lastName: 'Ottenbreit',
            number: 4,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7804.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '5bd638a01be89cc3172095a7', firstName: 'Turner', lastName: 'Ottenbreit' },
              query: 'player-5bd638a01be89cc3172095a7.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '0f46c3342e7ae911e5b4c51b',
            externalId: '7294',
            firstName: 'Kayle',
            lastName: 'Doetzel',
            number: 7,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7294.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '0f46c3342e7ae911e5b4c51b', firstName: 'Kayle', lastName: 'Doetzel' },
              query: 'player-0f46c3342e7ae911e5b4c51b.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 4 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '11939bb3d311e552551149a7',
            externalId: '8589',
            firstName: 'Joseph',
            lastName: 'Garreffa',
            number: 8,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8589.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '11939bb3d311e552551149a7', firstName: 'Joseph', lastName: 'Garreffa' },
              query: 'player-11939bb3d311e552551149a7.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 4 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '332ed900231c998bf014b024',
            externalId: '8590',
            firstName: 'Kameron',
            lastName: 'Kielly',
            number: 11,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8590.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '332ed900231c998bf014b024', firstName: 'Kameron', lastName: 'Kielly' },
              query: 'player-332ed900231c998bf014b024.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 3 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '212a4bd6d0554097749049dc',
            externalId: '8228',
            firstName: 'Les',
            lastName: 'Lancaster',
            number: 14,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8228.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '212a4bd6d0554097749049dc', firstName: 'Les', lastName: 'Lancaster' },
              query: 'player-212a4bd6d0554097749049dc.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '00a32b66acc565ea36f3da4c',
            externalId: '7971',
            firstName: 'Corey',
            lastName: 'Mackin',
            number: 15,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7971.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '00a32b66acc565ea36f3da4c', firstName: 'Corey', lastName: 'Mackin' },
              query: 'player-00a32b66acc565ea36f3da4c.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '79a3ef66f8c0814d33d6c626',
            externalId: '8591',
            firstName: 'Jake',
            lastName: 'McGrew',
            number: 18,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8591.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '79a3ef66f8c0814d33d6c626', firstName: 'Jake', lastName: 'McGrew' },
              query: 'player-79a3ef66f8c0814d33d6c626.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '79c565bdb4741a63002c7718',
            externalId: '5476',
            firstName: 'Alex',
            lastName: 'Lavoie',
            number: 19,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/5476.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '79c565bdb4741a63002c7718', firstName: 'Alex', lastName: 'Lavoie' },
              query: 'player-79c565bdb4741a63002c7718.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 6 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '679983d808be0653c9fca66b',
            externalId: '8428',
            firstName: 'Ben',
            lastName: 'Carroll',
            number: 20,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8428.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '679983d808be0653c9fca66b', firstName: 'Ben', lastName: 'Carroll' },
              query: 'player-679983d808be0653c9fca66b.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: -1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'ad2dba707ab7191a724ed410',
            externalId: '8227',
            firstName: 'Tyler',
            lastName: 'Sheehy',
            number: 22,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8227.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'ad2dba707ab7191a724ed410', firstName: 'Tyler', lastName: 'Sheehy' },
              query: 'player-ad2dba707ab7191a724ed410.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 5 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'ecf3577e363fe96167d0e44f',
            externalId: '8215',
            firstName: 'Cole',
            lastName: 'Fraser',
            number: 23,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8215.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'ecf3577e363fe96167d0e44f', firstName: 'Cole', lastName: 'Fraser' },
              query: 'player-ecf3577e363fe96167d0e44f.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '2fb7c365365b231e23884d29',
            externalId: '8592',
            firstName: 'Nolan',
            lastName: 'Kneen',
            number: 25,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8592.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '2fb7c365365b231e23884d29', firstName: 'Nolan', lastName: 'Kneen' },
              query: 'player-2fb7c365365b231e23884d29.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '803a2d79a240d332c8a7b0ae',
            externalId: '4143',
            firstName: 'Spencer',
            lastName: 'Asuchak',
            number: 26,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Center',
              shortName: 'C',
              category: 'Forwards',
              order: 2,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/4143.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '803a2d79a240d332c8a7b0ae', firstName: 'Spencer', lastName: 'Asuchak' },
              query: 'player-803a2d79a240d332c8a7b0ae.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '6ca34a1a1c993970f7421ac0',
            externalId: '8604',
            firstName: 'Jake',
            lastName: 'Gricius',
            number: 28,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8604.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '6ca34a1a1c993970f7421ac0', firstName: 'Jake', lastName: 'Gricius' },
              query: 'player-6ca34a1a1c993970f7421ac0.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: 'cb0e2b04eef5ebb5cbf66954',
            externalId: '4986',
            firstName: 'Jesse',
            lastName: 'Mychan',
            number: 29,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/4986.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: 'cb0e2b04eef5ebb5cbf66954', firstName: 'Jesse', lastName: 'Mychan' },
              query: 'player-cb0e2b04eef5ebb5cbf66954.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 4 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '25b4a308bb4a77047699bf22',
            externalId: '7991',
            firstName: 'Josh',
            lastName: 'Lammon',
            number: 40,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Center',
              shortName: 'C',
              category: 'Forwards',
              order: 2,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/7991.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '25b4a308bb4a77047699bf22', firstName: 'Josh', lastName: 'Lammon' },
              query: 'player-25b4a308bb4a77047699bf22.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 0 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '947eb66cb17d604fec33a1b6',
            externalId: '4676',
            firstName: 'Matt',
            lastName: 'Register',
            number: 43,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Defenseman',
              shortName: 'D',
              category: 'Defensemen',
              order: 5,
              categoryOrder: 2,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/4676.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '947eb66cb17d604fec33a1b6', firstName: 'Matt', lastName: 'Register' },
              query: 'player-947eb66cb17d604fec33a1b6.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 4 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 2 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
          {
            _type: 'Corebine.Core.Sport.Player',
            _entityId: '9ee4bcd2c607e6d7e814a747',
            externalId: '8593',
            firstName: 'Zane',
            lastName: 'Franklin',
            number: 44,
            position: {
              _type: 'Corebine.Core.Sport.Athlete.Position',
              name: 'Forward',
              shortName: 'F',
              category: 'Forwards',
              order: 1,
              categoryOrder: 1,
            },
            avatar: { _type: 'Corebine.Core.Image.Generic', url: 'https://assets.leaguestat.com/echl/120x160/8593.jpg' },
            source: {
              _type: 'Corebine.Core.Feed.Sport',
              feedType: 'player',
              person: { _type: 'Corebine.Core.Sport.Player', _entityId: '9ee4bcd2c607e6d7e814a747', firstName: 'Zane', lastName: 'Franklin' },
              query: 'player-9ee4bcd2c607e6d7e814a747.json',
            },
            stats: {
              _type: 'Corebine.Core.Sport.Athlete.Stats',
              properties: [
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Goals', shortName: 'G', value: 0 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Assists', shortName: 'A', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Plus/Minus', shortName: '+/-', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Shots', shortName: 'SH', value: 1 },
                { _type: 'Corebine.Core.Type.Property.Integer', name: 'Penalty Minutes', shortName: 'PIM', value: 2 },
              ],
            },
          },
        ],
      },
    },
    link: {
      _type: 'Corebine.Core.Type.Link.Internal',
      pageEntityId: '1',
      url: '/matches/726aeb7bddff5b8567b9230d/wichita-thunder-vs-allen-americans',
    },
  },
  errors: [],
}
