module.exports = {
  GoalieLevels: [],
  AllGoalieGames: [],
  SkaterLevels: [
    {
      LevelName: 'Liiga',
      LevelID: '64',
      LevelSeries: [
        {
          SerieName: 'Liigan runkosarja',
          SerieID: '1188',
          SerieGames: [
            {
              GameDate: '06.11.2020',
              GameID: '228',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'SaiPa',
              ReportEnabled: '0',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
          ],
          PlayedSerieGames: '1',
          SerieGoals: '0',
          SerieAssists: '0',
          SeriePoints: '0',
          SeriePenMinutes: '0',
          SerieTeams: [{ TeamName: 'Kärpät' }],
        },
        {
          SerieName: 'Liigan harjoitusottelut',
          SerieID: '1194',
          SerieGames: [
            {
              GameDate: '20.08.2020',
              GameID: '9390',
              HomeTeamName: 'Hokki',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '0',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '1',
              SkaterPoints: '1',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '19.08.2020',
              GameID: '9393',
              HomeTeamName: 'RoKi',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '0',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '1',
              SkaterPoints: '1',
              SkaterPenMinutes: '0',
            },
          ],
          PlayedSerieGames: '2',
          SerieGoals: '0',
          SerieAssists: '2',
          SeriePoints: '2',
          SeriePenMinutes: '0',
          SerieTeams: [{ TeamName: 'Kärpät' }],
        },
      ],
      PlayedLevelGames: '3',
      LevelGoals: '0',
      LevelAssists: '2',
      LevelPoints: '2',
      LevelPenMinutes: '0',
      LevelTeams: [{ TeamName: 'Kärpät' }],
    },
    {
      LevelName: 'U20 SM-sarja',
      LevelID: '77',
      LevelSeries: [
        {
          SerieName: 'U20 SM-sarja, alkusarja',
          SerieID: '782',
          SerieGames: [
            {
              GameDate: '24.10.2020',
              GameID: '8603',
              HomeTeamName: 'K-Espoo',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '1',
              SkaterPoints: '1',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '23.10.2020',
              GameID: '8660',
              HomeTeamName: 'TPS',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '16.10.2020',
              GameID: '8594',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'JYP',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '1',
              SkaterPoints: '1',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '10.10.2020',
              GameID: '8537',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'Sport',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '2',
              SkaterPoints: '2',
              SkaterPenMinutes: '2',
            },
            {
              GameDate: '09.10.2020',
              GameID: '8613',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'KooKoo',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '07.10.2020',
              GameID: '8575',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'Jukurit',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '2',
              SkaterPoints: '2',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '03.10.2020',
              GameID: '8743',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'Ässät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '02.10.2020',
              GameID: '8565',
              HomeTeamName: 'Jokerit',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '4',
            },
            {
              GameDate: '27.09.2020',
              GameID: '8726',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'KalPa',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '26.09.2020',
              GameID: '8748',
              HomeTeamName: 'Sport',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '20.09.2020',
              GameID: '8730',
              HomeTeamName: 'Tappara',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '2',
            },
            {
              GameDate: '19.09.2020',
              GameID: '8801',
              HomeTeamName: 'Sport',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '1',
              SkaterAssists: '0',
              SkaterPoints: '1',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '12.09.2020',
              GameID: '8797',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'Tappara',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '1',
              SkaterPoints: '1',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '11.09.2020',
              GameID: '8800',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'JYP',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
            {
              GameDate: '05.09.2020',
              GameID: '8793',
              HomeTeamName: 'Ilves',
              AwayTeamName: 'Kärpät',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '2',
              SkaterAssists: '0',
              SkaterPoints: '2',
              SkaterPenMinutes: '4',
            },
            {
              GameDate: '04.09.2020',
              GameID: '8790',
              HomeTeamName: 'Kärpät',
              AwayTeamName: 'KalPa',
              ReportEnabled: '1',
              StatsEnabled: '1',
              SkaterGoals: '0',
              SkaterAssists: '0',
              SkaterPoints: '0',
              SkaterPenMinutes: '0',
            },
          ],
          PlayedSerieGames: '16',
          SerieGoals: '3',
          SerieAssists: '7',
          SeriePoints: '10',
          SeriePenMinutes: '12',
          SerieTeams: [{ TeamName: 'Kärpät' }],
        },
      ],
      PlayedLevelGames: '16',
      LevelGoals: '3',
      LevelAssists: '7',
      LevelPoints: '10',
      LevelPenMinutes: '12',
      LevelTeams: [{ TeamName: 'Kärpät' }],
    },
  ],
  AllSkaterGames: [
    {
      GameDate: '06.11.2020',
      GameID: '228',
      LevelID: '64',
      LevelName: 'Liiga',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'SaiPa',
      ReportEnabled: '0',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '24.10.2020',
      GameID: '8603',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'K-Espoo',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '1',
      SkaterPoints: '1',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '23.10.2020',
      GameID: '8660',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'TPS',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '16.10.2020',
      GameID: '8594',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'JYP',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '1',
      SkaterPoints: '1',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '10.10.2020',
      GameID: '8537',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'Sport',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '2',
      SkaterPoints: '2',
      SkaterPenMinutes: '2',
    },
    {
      GameDate: '09.10.2020',
      GameID: '8613',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'KooKoo',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '07.10.2020',
      GameID: '8575',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'Jukurit',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '2',
      SkaterPoints: '2',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '03.10.2020',
      GameID: '8743',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'Ässät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '02.10.2020',
      GameID: '8565',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Jokerit',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '4',
    },
    {
      GameDate: '27.09.2020',
      GameID: '8726',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'KalPa',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '26.09.2020',
      GameID: '8748',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Sport',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '20.09.2020',
      GameID: '8730',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Tappara',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '2',
    },
    {
      GameDate: '19.09.2020',
      GameID: '8801',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Sport',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '1',
      SkaterAssists: '0',
      SkaterPoints: '1',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '12.09.2020',
      GameID: '8797',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'Tappara',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '1',
      SkaterPoints: '1',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '11.09.2020',
      GameID: '8800',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'JYP',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '05.09.2020',
      GameID: '8793',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Ilves',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '2',
      SkaterAssists: '0',
      SkaterPoints: '2',
      SkaterPenMinutes: '4',
    },
    {
      GameDate: '04.09.2020',
      GameID: '8790',
      LevelID: '77',
      LevelName: 'U20 SM-sarja',
      HomeTeamName: 'Kärpät',
      AwayTeamName: 'KalPa',
      ReportEnabled: '1',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '0',
      SkaterPoints: '0',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '20.08.2020',
      GameID: '9390',
      LevelID: '64',
      LevelName: 'Liiga',
      HomeTeamName: 'Hokki',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '0',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '1',
      SkaterPoints: '1',
      SkaterPenMinutes: '0',
    },
    {
      GameDate: '19.08.2020',
      GameID: '9393',
      LevelID: '64',
      LevelName: 'Liiga',
      HomeTeamName: 'RoKi',
      AwayTeamName: 'Kärpät',
      ReportEnabled: '0',
      StatsEnabled: '1',
      SkaterGoals: '0',
      SkaterAssists: '1',
      SkaterPoints: '1',
      SkaterPenMinutes: '0',
    },
  ],
}
